### ISSUE TITLE
Null pointer dereference during garbage collection

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3463]
The following input demonstrates a crash:
```ruby
def method_missing(a, *b)
  c
end

d
```
ASAN report:
```
ASAN:DEADLYSIGNAL
=================================================================
==82122==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010fb05d1d bp 0x7fff50178eb0 sp 0x7fff50178ca0 T0)
    #0 0x10fb05d1c in mark_context_stack gc.c:554
    #1 0x10fb052c6 in mark_context gc.c:571
    #2 0x10fb04077 in root_scan_phase gc.c:873
    #3 0x10fb03250 in incremental_gc gc.c:1080
    #4 0x10faff4ec in incremental_gc_step gc.c:1121
    #5 0x10fafe6fc in mrb_incremental_gc gc.c:1165
    #6 0x10fafe078 in mrb_obj_alloc gc.c:507
    #7 0x10fa80c93 in ary_new_capa array.c:30
    #8 0x10fa80a77 in mrb_ary_new_capa array.c:41
    #9 0x10fbf452a in mrb_vm_exec vm.c:1561
    #10 0x10fbe2589 in mrb_vm_run vm.c:815
    #11 0x10fc13a19 in mrb_top_run vm.c:2569
    #12 0x10fce17b5 in mrb_load_exec parse.y:5755
    #13 0x10fce25c5 in mrb_load_file_cxt parse.y:5764
    #14 0x10fa7f01a in main mruby.c:232
    #15 0x7fffb4357254 in start (libdyld.dylib+0x5254)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV gc.c:554 in mark_context_stack
==82122==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/ston3

**Comment by clayton-shopify** [comment]
It looks like https://github.com/mruby/mruby/commit/736be0e98b9e1136a4dc7cb2dd05e1f33728f767 fixed this.
