### ISSUE TITLE
Null pointer dereference in mark_context_stack

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3488]
The following input demonstrates a crash:
```ruby
def one
  too { yield }
end

def too
  yield
ensure
  one { break }
end

one
```
This is recursive code but it seems to fail in a garbage collection well before overflowing the stack.

ASAN report:
```
ASAN:DEADLYSIGNAL
=================================================================
==93293==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010bde533d bp 0x7fff53c2efb0 sp 0x7fff53c2eda0 T0)
    #0 0x10bde533c in mark_context_stack gc.c:554
    #1 0x10bde48e6 in mark_context gc.c:571
    #2 0x10bde3697 in root_scan_phase gc.c:874
    #3 0x10bde2870 in incremental_gc gc.c:1081
    #4 0x10bddeb0c in incremental_gc_step gc.c:1122
    #5 0x10bdddd1c in mrb_incremental_gc gc.c:1166
    #6 0x10bddd698 in mrb_obj_alloc gc.c:507
    #7 0x10be46543 in mrb_proc_new proc.c:22
    #8 0x10be4682c in mrb_closure_new proc.c:69
    #9 0x10bee9df3 in mrb_vm_exec vm.c:2362
    #10 0x10bec1a69 in mrb_vm_run vm.c:822
    #11 0x10bebabce in mrb_run vm.c:2570
    #12 0x10bef082e in ecall vm.c:314
    #13 0x10bed7972 in mrb_vm_exec vm.c:1748
    #14 0x10bec1a69 in mrb_vm_run vm.c:822
    #15 0x10bebabce in mrb_run vm.c:2570
    #16 0x10bef082e in ecall vm.c:314
    #17 0x10bed7972 in mrb_vm_exec vm.c:1748
    #18 0x10bec1a69 in mrb_vm_run vm.c:822
    #19 0x10bebabce in mrb_run vm.c:2570
    #20 0x10bef082e in ecall vm.c:314
    #21 0x10bed7972 in mrb_vm_exec vm.c:1748
    #22 0x10bec1a69 in mrb_vm_run vm.c:822
    #23 0x10bebabce in mrb_run vm.c:2570
    #24 0x10bef082e in ecall vm.c:314
    #25 0x10bed7972 in mrb_vm_exec vm.c:1748
    #26 0x10bec1a69 in mrb_vm_run vm.c:822
    #27 0x10bebabce in mrb_run vm.c:2570
    #28 0x10bef082e in ecall vm.c:314
    #29 0x10bed7972 in mrb_vm_exec vm.c:1748
    #30 0x10bec1a69 in mrb_vm_run vm.c:822
    #31 0x10bebabce in mrb_run vm.c:2570
    #32 0x10bef082e in ecall vm.c:314
    #33 0x10bed7972 in mrb_vm_exec vm.c:1748
    #34 0x10bec1a69 in mrb_vm_run vm.c:822
    #35 0x10bebabce in mrb_run vm.c:2570
    #36 0x10bef082e in ecall vm.c:314
    #37 0x10bed7972 in mrb_vm_exec vm.c:1748
    #38 0x10bec1a69 in mrb_vm_run vm.c:822
    #39 0x10bebabce in mrb_run vm.c:2570
    #40 0x10bef082e in ecall vm.c:314
    #41 0x10bed7972 in mrb_vm_exec vm.c:1748
    #42 0x10bec1a69 in mrb_vm_run vm.c:822
    #43 0x10bebabce in mrb_run vm.c:2570
    #44 0x10bef082e in ecall vm.c:314
    #45 0x10bed7972 in mrb_vm_exec vm.c:1748
    #46 0x10bec1a69 in mrb_vm_run vm.c:822
    #47 0x10bebabce in mrb_run vm.c:2570
    #48 0x10bef082e in ecall vm.c:314
    #49 0x10bed7972 in mrb_vm_exec vm.c:1748
    #50 0x10bec1a69 in mrb_vm_run vm.c:822
    #51 0x10bebabce in mrb_run vm.c:2570
    #52 0x10bef082e in ecall vm.c:314
    #53 0x10bed7972 in mrb_vm_exec vm.c:1748
    #54 0x10bec1a69 in mrb_vm_run vm.c:822
    #55 0x10bebabce in mrb_run vm.c:2570
    #56 0x10bef082e in ecall vm.c:314
    #57 0x10bed7972 in mrb_vm_exec vm.c:1748
    #58 0x10bec1a69 in mrb_vm_run vm.c:822
    #59 0x10bebabce in mrb_run vm.c:2570
    #60 0x10bef082e in ecall vm.c:314
    #61 0x10bed7972 in mrb_vm_exec vm.c:1748
    #62 0x10bec1a69 in mrb_vm_run vm.c:822
    #63 0x10bebabce in mrb_run vm.c:2570
    #64 0x10bef082e in ecall vm.c:314
    #65 0x10bed7972 in mrb_vm_exec vm.c:1748
    #66 0x10bec1a69 in mrb_vm_run vm.c:822
    #67 0x10bebabce in mrb_run vm.c:2570
    #68 0x10bef082e in ecall vm.c:314
    #69 0x10bed7972 in mrb_vm_exec vm.c:1748
    #70 0x10bec1a69 in mrb_vm_run vm.c:822
    #71 0x10bebabce in mrb_run vm.c:2570
    #72 0x10bef082e in ecall vm.c:314
    #73 0x10bed7972 in mrb_vm_exec vm.c:1748
    #74 0x10bec1a69 in mrb_vm_run vm.c:822
    #75 0x10bebabce in mrb_run vm.c:2570
    #76 0x10bef082e in ecall vm.c:314
    #77 0x10bed7972 in mrb_vm_exec vm.c:1748
    #78 0x10bec1a69 in mrb_vm_run vm.c:822
    #79 0x10bebabce in mrb_run vm.c:2570
    #80 0x10bef082e in ecall vm.c:314
    #81 0x10bed7972 in mrb_vm_exec vm.c:1748
    #82 0x10bec1a69 in mrb_vm_run vm.c:822
    #83 0x10bebabce in mrb_run vm.c:2570
    #84 0x10bef082e in ecall vm.c:314
    #85 0x10bed7972 in mrb_vm_exec vm.c:1748
    #86 0x10bec1a69 in mrb_vm_run vm.c:822
    #87 0x10bebabce in mrb_run vm.c:2570
    #88 0x10bef082e in ecall vm.c:314
    #89 0x10bed7972 in mrb_vm_exec vm.c:1748
    #90 0x10bec1a69 in mrb_vm_run vm.c:822
    #91 0x10bebabce in mrb_run vm.c:2570
    #92 0x10bef082e in ecall vm.c:314
    #93 0x10bed7972 in mrb_vm_exec vm.c:1748
    #94 0x10bec1a69 in mrb_vm_run vm.c:822
    #95 0x10bebabce in mrb_run vm.c:2570
    #96 0x10bef082e in ecall vm.c:314
    #97 0x10bed7972 in mrb_vm_exec vm.c:1748
    #98 0x10bec1a69 in mrb_vm_run vm.c:822
    #99 0x10bebabce in mrb_run vm.c:2570
    #100 0x10bef082e in ecall vm.c:314
    #101 0x10bed7972 in mrb_vm_exec vm.c:1748
    #102 0x10bec1a69 in mrb_vm_run vm.c:822
    #103 0x10bebabce in mrb_run vm.c:2570
    #104 0x10bef082e in ecall vm.c:314
    #105 0x10bed7972 in mrb_vm_exec vm.c:1748
    #106 0x10bec1a69 in mrb_vm_run vm.c:822
    #107 0x10bebabce in mrb_run vm.c:2570
    #108 0x10bef082e in ecall vm.c:314
    #109 0x10bed7972 in mrb_vm_exec vm.c:1748
    #110 0x10bec1a69 in mrb_vm_run vm.c:822
    #111 0x10bebabce in mrb_run vm.c:2570
    #112 0x10bef082e in ecall vm.c:314
    #113 0x10bed7972 in mrb_vm_exec vm.c:1748
    #114 0x10bec1a69 in mrb_vm_run vm.c:822
    #115 0x10bebabce in mrb_run vm.c:2570
    #116 0x10bef082e in ecall vm.c:314
    #117 0x10bed7972 in mrb_vm_exec vm.c:1748
    #118 0x10bec1a69 in mrb_vm_run vm.c:822
    #119 0x10bebabce in mrb_run vm.c:2570
    #120 0x10bef082e in ecall vm.c:314
    #121 0x10bed7972 in mrb_vm_exec vm.c:1748
    #122 0x10bec1a69 in mrb_vm_run vm.c:822
    #123 0x10bebabce in mrb_run vm.c:2570
    #124 0x10bef082e in ecall vm.c:314
    #125 0x10bed7972 in mrb_vm_exec vm.c:1748
    #126 0x10bec1a69 in mrb_vm_run vm.c:822
    #127 0x10bebabce in mrb_run vm.c:2570
    #128 0x10bef082e in ecall vm.c:314
    #129 0x10bed7972 in mrb_vm_exec vm.c:1748
    #130 0x10bec1a69 in mrb_vm_run vm.c:822
    #131 0x10bebabce in mrb_run vm.c:2570
    #132 0x10bef082e in ecall vm.c:314
    #133 0x10bed7972 in mrb_vm_exec vm.c:1748
    #134 0x10bec1a69 in mrb_vm_run vm.c:822
    #135 0x10bebabce in mrb_run vm.c:2570
    #136 0x10bef082e in ecall vm.c:314
    #137 0x10bed7972 in mrb_vm_exec vm.c:1748
    #138 0x10bec1a69 in mrb_vm_run vm.c:822
    #139 0x10bebabce in mrb_run vm.c:2570
    #140 0x10bef082e in ecall vm.c:314
    #141 0x10bed7972 in mrb_vm_exec vm.c:1748
    #142 0x10bec1a69 in mrb_vm_run vm.c:822
    #143 0x10bebabce in mrb_run vm.c:2570
    #144 0x10bef082e in ecall vm.c:314
    #145 0x10bed7972 in mrb_vm_exec vm.c:1748
    #146 0x10bec1a69 in mrb_vm_run vm.c:822
    #147 0x10bebabce in mrb_run vm.c:2570
    #148 0x10bef082e in ecall vm.c:314
    #149 0x10bed7972 in mrb_vm_exec vm.c:1748
    #150 0x10bec1a69 in mrb_vm_run vm.c:822
    #151 0x10bebabce in mrb_run vm.c:2570
    #152 0x10bef082e in ecall vm.c:314
    #153 0x10bed7972 in mrb_vm_exec vm.c:1748
    #154 0x10bec1a69 in mrb_vm_run vm.c:822
    #155 0x10bebabce in mrb_run vm.c:2570
    #156 0x10bef082e in ecall vm.c:314
    #157 0x10bed7972 in mrb_vm_exec vm.c:1748
    #158 0x10bec1a69 in mrb_vm_run vm.c:822
    #159 0x10bebabce in mrb_run vm.c:2570
    #160 0x10bef082e in ecall vm.c:314
    #161 0x10bed7972 in mrb_vm_exec vm.c:1748
    #162 0x10bec1a69 in mrb_vm_run vm.c:822
    #163 0x10bebabce in mrb_run vm.c:2570
    #164 0x10bef082e in ecall vm.c:314
    #165 0x10bed7972 in mrb_vm_exec vm.c:1748
    #166 0x10bec1a69 in mrb_vm_run vm.c:822
    #167 0x10bebabce in mrb_run vm.c:2570
    #168 0x10bef082e in ecall vm.c:314
    #169 0x10bed7972 in mrb_vm_exec vm.c:1748
    #170 0x10bec1a69 in mrb_vm_run vm.c:822
    #171 0x10bebabce in mrb_run vm.c:2570
    #172 0x10bef082e in ecall vm.c:314
    #173 0x10bed7972 in mrb_vm_exec vm.c:1748
    #174 0x10bec1a69 in mrb_vm_run vm.c:822
    #175 0x10bebabce in mrb_run vm.c:2570
    #176 0x10bef082e in ecall vm.c:314
    #177 0x10bed7972 in mrb_vm_exec vm.c:1748
    #178 0x10bec1a69 in mrb_vm_run vm.c:822
    #179 0x10bebabce in mrb_run vm.c:2570
    #180 0x10bef082e in ecall vm.c:314
    #181 0x10bed7972 in mrb_vm_exec vm.c:1748
    #182 0x10bec1a69 in mrb_vm_run vm.c:822
    #183 0x10bebabce in mrb_run vm.c:2570
    #184 0x10bef082e in ecall vm.c:314
    #185 0x10bed7972 in mrb_vm_exec vm.c:1748
    #186 0x10bec1a69 in mrb_vm_run vm.c:822
    #187 0x10bebabce in mrb_run vm.c:2570
    #188 0x10bef082e in ecall vm.c:314
    #189 0x10bed7972 in mrb_vm_exec vm.c:1748
    #190 0x10bec1a69 in mrb_vm_run vm.c:822
    #191 0x10bebabce in mrb_run vm.c:2570
    #192 0x10bef082e in ecall vm.c:314
    #193 0x10bed7972 in mrb_vm_exec vm.c:1748
    #194 0x10bec1a69 in mrb_vm_run vm.c:822
    #195 0x10bebabce in mrb_run vm.c:2570
    #196 0x10bef082e in ecall vm.c:314
    #197 0x10bed7972 in mrb_vm_exec vm.c:1748
    #198 0x10bec1a69 in mrb_vm_run vm.c:822
    #199 0x10bebabce in mrb_run vm.c:2570
    #200 0x10bef082e in ecall vm.c:314
    #201 0x10bed7972 in mrb_vm_exec vm.c:1748
    #202 0x10bec1a69 in mrb_vm_run vm.c:822
    #203 0x10bebabce in mrb_run vm.c:2570
    #204 0x10bef082e in ecall vm.c:314
    #205 0x10bed7972 in mrb_vm_exec vm.c:1748
    #206 0x10bec1a69 in mrb_vm_run vm.c:822
    #207 0x10bebabce in mrb_run vm.c:2570
    #208 0x10bef082e in ecall vm.c:314
    #209 0x10bed7972 in mrb_vm_exec vm.c:1748
    #210 0x10bec1a69 in mrb_vm_run vm.c:822
    #211 0x10bebabce in mrb_run vm.c:2570
    #212 0x10bef082e in ecall vm.c:314
    #213 0x10bed7972 in mrb_vm_exec vm.c:1748
    #214 0x10bec1a69 in mrb_vm_run vm.c:822
    #215 0x10bebabce in mrb_run vm.c:2570
    #216 0x10bef082e in ecall vm.c:314
    #217 0x10bed7972 in mrb_vm_exec vm.c:1748
    #218 0x10bec1a69 in mrb_vm_run vm.c:822
    #219 0x10bebabce in mrb_run vm.c:2570
    #220 0x10bef082e in ecall vm.c:314
    #221 0x10bed7972 in mrb_vm_exec vm.c:1748
    #222 0x10bec1a69 in mrb_vm_run vm.c:822
    #223 0x10bebabce in mrb_run vm.c:2570
    #224 0x10bef082e in ecall vm.c:314
    #225 0x10bed7972 in mrb_vm_exec vm.c:1748
    #226 0x10bec1a69 in mrb_vm_run vm.c:822
    #227 0x10bebabce in mrb_run vm.c:2570
    #228 0x10bef082e in ecall vm.c:314
    #229 0x10bed7972 in mrb_vm_exec vm.c:1748
    #230 0x10bec1a69 in mrb_vm_run vm.c:822
    #231 0x10bebabce in mrb_run vm.c:2570
    #232 0x10bef082e in ecall vm.c:314
    #233 0x10bed7972 in mrb_vm_exec vm.c:1748
    #234 0x10bec1a69 in mrb_vm_run vm.c:822
    #235 0x10bebabce in mrb_run vm.c:2570
    #236 0x10bef082e in ecall vm.c:314
    #237 0x10bed7972 in mrb_vm_exec vm.c:1748
    #238 0x10bec1a69 in mrb_vm_run vm.c:822
    #239 0x10bebabce in mrb_run vm.c:2570
    #240 0x10bef082e in ecall vm.c:314
    #241 0x10bed7972 in mrb_vm_exec vm.c:1748
    #242 0x10bec1a69 in mrb_vm_run vm.c:822
    #243 0x10bebabce in mrb_run vm.c:2570
    #244 0x10bef082e in ecall vm.c:314
    #245 0x10bed7972 in mrb_vm_exec vm.c:1748
    #246 0x10bec1a69 in mrb_vm_run vm.c:822
    #247 0x10bebabce in mrb_run vm.c:2570
    #248 0x10bef082e in ecall vm.c:314
    #249 0x10bed7972 in mrb_vm_exec vm.c:1748
    #250 0x10bec1a69 in mrb_vm_run vm.c:822
    #251 0x10bebabce in mrb_run vm.c:2570
    #252 0x10bef082e in ecall vm.c:314
    #253 0x10bed7972 in mrb_vm_exec vm.c:1748
    #254 0x10bec1a69 in mrb_vm_run vm.c:822
    #255 0x10bebabce in mrb_run vm.c:2570

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV gc.c:554 in mark_context_stack
==93293==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/ston3

**Comment by matz** [comment]
This is caused by #3359

**Comment by matz** [comment]
No #3359 is not related.
I couldn't reproduce the problem any longer. Hopefully, it's fixed.

**Comment by clayton-shopify** [comment]
@matz It seems this (and a few other crashes) may have been fixed by https://github.com/mruby/mruby/commit/ab25eaea2345577b4e28672908f0190ce6b21684. I'll close off the ones that are fixed now.

**Comment by clayton-shopify** [comment]
This seems to be resolved now.
