### ISSUE TITLE
Null pointer dereference in OP_LOADSELF

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3512]
The following input demonstrates a crash:
```ruby
def to_str
  @b + + -> {}
rescue to_str
  @b + + -> {}
rescue ""
end

class A < to_str
end
```
This seems to result in recursion for a short time, but a null pointer dereference quickly occurs:
```
* thread #1: tid = 0x5cce1, 0x00007fffaf668f3d libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 157, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007fffaf668f3d libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 157
libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell:
->  0x7fffaf668f3d <+157>: movq   (%rsi), %rcx
    0x7fffaf668f40 <+160>: movq   (%rsi,%rdx), %r8
    0x7fffaf668f44 <+164>: movq   %rcx, (%rdi)
    0x7fffaf668f47 <+167>: movq   %r8, (%rdi,%rdx)
(lldb) frame select 2
frame #2: 0x0000000100167ed3 mruby`mrb_vm_exec(mrb=0x000061400000fe40, proc=0x000062f000002c20, pc=0x000060b00000a8cc) + 7619 at vm.c:914
   911
   912 	    CASE(OP_LOADSELF) {
   913 	      /* A      R(A) := self */
-> 914 	      regs[GETARG_A(i)] = regs[0];
   915 	      NEXT;
   916 	    }
   917
(lldb) print mrb->c->stack
(mrb_value *) $0 = 0x0000000000000000
```
ASAN report:
```
==49854==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fffaf668f3d bp 0x7fff52677a00 sp 0x7fff52677a00 T0)
    #0 0x7fffaf668f3c in _platform_memmove$VARIANT$Haswell (libsystem_platform.dylib+0x5f3c)
    #1 0x10d839bf8 in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib+0x41bf8)
    #2 0x10d5fbed2 in mrb_vm_exec vm.c:914
    #3 0x10d5f9f99 in mrb_vm_run vm.c:820
    #4 0x10d5f301e in mrb_run vm.c:2604
    #5 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #6 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #7 0x10d572c9e in convert_type object.c:320
    #8 0x10d573dba in mrb_check_convert_type object.c:356
    #9 0x10d5985f5 in mrb_str_to_str string.c:1028
    #10 0x10d5abeb6 in mrb_str_append string.c:2605
    #11 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #12 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #13 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #14 0x10d53edb2 in mrb_method_missing kernel.c:926
    #15 0x10d603c18 in mrb_vm_exec vm.c:1229
    #16 0x10d5f9f99 in mrb_vm_run vm.c:820
    #17 0x10d5f301e in mrb_run vm.c:2604
    #18 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #19 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #20 0x10d572c9e in convert_type object.c:320
    #21 0x10d573dba in mrb_check_convert_type object.c:356
    #22 0x10d5985f5 in mrb_str_to_str string.c:1028
    #23 0x10d5abeb6 in mrb_str_append string.c:2605
    #24 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #25 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #26 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #27 0x10d53edb2 in mrb_method_missing kernel.c:926
    #28 0x10d603c18 in mrb_vm_exec vm.c:1229
    #29 0x10d5f9f99 in mrb_vm_run vm.c:820
    #30 0x10d5f301e in mrb_run vm.c:2604
    #31 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #32 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #33 0x10d572c9e in convert_type object.c:320
    #34 0x10d573dba in mrb_check_convert_type object.c:356
    #35 0x10d5985f5 in mrb_str_to_str string.c:1028
    #36 0x10d5abeb6 in mrb_str_append string.c:2605
    #37 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #38 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #39 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #40 0x10d53edb2 in mrb_method_missing kernel.c:926
    #41 0x10d603c18 in mrb_vm_exec vm.c:1229
    #42 0x10d5f9f99 in mrb_vm_run vm.c:820
    #43 0x10d5f301e in mrb_run vm.c:2604
    #44 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #45 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #46 0x10d572c9e in convert_type object.c:320
    #47 0x10d573dba in mrb_check_convert_type object.c:356
    #48 0x10d5985f5 in mrb_str_to_str string.c:1028
    #49 0x10d5abeb6 in mrb_str_append string.c:2605
    #50 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #51 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #52 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #53 0x10d53edb2 in mrb_method_missing kernel.c:926
    #54 0x10d603c18 in mrb_vm_exec vm.c:1229
    #55 0x10d5f9f99 in mrb_vm_run vm.c:820
    #56 0x10d5f301e in mrb_run vm.c:2604
    #57 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #58 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #59 0x10d572c9e in convert_type object.c:320
    #60 0x10d573dba in mrb_check_convert_type object.c:356
    #61 0x10d5985f5 in mrb_str_to_str string.c:1028
    #62 0x10d5abeb6 in mrb_str_append string.c:2605
    #63 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #64 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #65 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #66 0x10d53edb2 in mrb_method_missing kernel.c:926
    #67 0x10d603c18 in mrb_vm_exec vm.c:1229
    #68 0x10d5f9f99 in mrb_vm_run vm.c:820
    #69 0x10d5f301e in mrb_run vm.c:2604
    #70 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #71 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #72 0x10d572c9e in convert_type object.c:320
    #73 0x10d573dba in mrb_check_convert_type object.c:356
    #74 0x10d5985f5 in mrb_str_to_str string.c:1028
    #75 0x10d5abeb6 in mrb_str_append string.c:2605
    #76 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #77 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #78 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #79 0x10d53edb2 in mrb_method_missing kernel.c:926
    #80 0x10d603c18 in mrb_vm_exec vm.c:1229
    #81 0x10d5f9f99 in mrb_vm_run vm.c:820
    #82 0x10d5f301e in mrb_run vm.c:2604
    #83 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #84 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #85 0x10d572c9e in convert_type object.c:320
    #86 0x10d573dba in mrb_check_convert_type object.c:356
    #87 0x10d5985f5 in mrb_str_to_str string.c:1028
    #88 0x10d5abeb6 in mrb_str_append string.c:2605
    #89 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #90 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #91 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #92 0x10d53edb2 in mrb_method_missing kernel.c:926
    #93 0x10d603c18 in mrb_vm_exec vm.c:1229
    #94 0x10d5f9f99 in mrb_vm_run vm.c:820
    #95 0x10d5f301e in mrb_run vm.c:2604
    #96 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #97 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #98 0x10d572c9e in convert_type object.c:320
    #99 0x10d573dba in mrb_check_convert_type object.c:356
    #100 0x10d5985f5 in mrb_str_to_str string.c:1028
    #101 0x10d5abeb6 in mrb_str_append string.c:2605
    #102 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #103 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #104 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #105 0x10d53edb2 in mrb_method_missing kernel.c:926
    #106 0x10d603c18 in mrb_vm_exec vm.c:1229
    #107 0x10d5f9f99 in mrb_vm_run vm.c:820
    #108 0x10d5f301e in mrb_run vm.c:2604
    #109 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #110 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #111 0x10d572c9e in convert_type object.c:320
    #112 0x10d573dba in mrb_check_convert_type object.c:356
    #113 0x10d5985f5 in mrb_str_to_str string.c:1028
    #114 0x10d5abeb6 in mrb_str_append string.c:2605
    #115 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #116 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #117 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #118 0x10d53edb2 in mrb_method_missing kernel.c:926
    #119 0x10d603c18 in mrb_vm_exec vm.c:1229
    #120 0x10d5f9f99 in mrb_vm_run vm.c:820
    #121 0x10d5f301e in mrb_run vm.c:2604
    #122 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #123 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #124 0x10d572c9e in convert_type object.c:320
    #125 0x10d573dba in mrb_check_convert_type object.c:356
    #126 0x10d5985f5 in mrb_str_to_str string.c:1028
    #127 0x10d5abeb6 in mrb_str_append string.c:2605
    #128 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #129 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #130 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #131 0x10d53edb2 in mrb_method_missing kernel.c:926
    #132 0x10d603c18 in mrb_vm_exec vm.c:1229
    #133 0x10d5f9f99 in mrb_vm_run vm.c:820
    #134 0x10d5f301e in mrb_run vm.c:2604
    #135 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #136 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #137 0x10d572c9e in convert_type object.c:320
    #138 0x10d573dba in mrb_check_convert_type object.c:356
    #139 0x10d5985f5 in mrb_str_to_str string.c:1028
    #140 0x10d5abeb6 in mrb_str_append string.c:2605
    #141 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #142 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #143 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #144 0x10d53edb2 in mrb_method_missing kernel.c:926
    #145 0x10d603c18 in mrb_vm_exec vm.c:1229
    #146 0x10d5f9f99 in mrb_vm_run vm.c:820
    #147 0x10d5f301e in mrb_run vm.c:2604
    #148 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #149 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #150 0x10d572c9e in convert_type object.c:320
    #151 0x10d573dba in mrb_check_convert_type object.c:356
    #152 0x10d5985f5 in mrb_str_to_str string.c:1028
    #153 0x10d5abeb6 in mrb_str_append string.c:2605
    #154 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #155 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #156 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #157 0x10d53edb2 in mrb_method_missing kernel.c:926
    #158 0x10d603c18 in mrb_vm_exec vm.c:1229
    #159 0x10d5f9f99 in mrb_vm_run vm.c:820
    #160 0x10d5f301e in mrb_run vm.c:2604
    #161 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #162 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #163 0x10d572c9e in convert_type object.c:320
    #164 0x10d573dba in mrb_check_convert_type object.c:356
    #165 0x10d5985f5 in mrb_str_to_str string.c:1028
    #166 0x10d5abeb6 in mrb_str_append string.c:2605
    #167 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #168 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #169 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #170 0x10d53edb2 in mrb_method_missing kernel.c:926
    #171 0x10d603c18 in mrb_vm_exec vm.c:1229
    #172 0x10d5f9f99 in mrb_vm_run vm.c:820
    #173 0x10d5f301e in mrb_run vm.c:2604
    #174 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #175 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #176 0x10d572c9e in convert_type object.c:320
    #177 0x10d573dba in mrb_check_convert_type object.c:356
    #178 0x10d5985f5 in mrb_str_to_str string.c:1028
    #179 0x10d5abeb6 in mrb_str_append string.c:2605
    #180 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #181 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #182 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #183 0x10d53edb2 in mrb_method_missing kernel.c:926
    #184 0x10d603c18 in mrb_vm_exec vm.c:1229
    #185 0x10d5f9f99 in mrb_vm_run vm.c:820
    #186 0x10d5f301e in mrb_run vm.c:2604
    #187 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #188 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #189 0x10d572c9e in convert_type object.c:320
    #190 0x10d573dba in mrb_check_convert_type object.c:356
    #191 0x10d5985f5 in mrb_str_to_str string.c:1028
    #192 0x10d5abeb6 in mrb_str_append string.c:2605
    #193 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #194 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #195 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #196 0x10d53edb2 in mrb_method_missing kernel.c:926
    #197 0x10d603c18 in mrb_vm_exec vm.c:1229
    #198 0x10d5f9f99 in mrb_vm_run vm.c:820
    #199 0x10d5f301e in mrb_run vm.c:2604
    #200 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #201 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #202 0x10d572c9e in convert_type object.c:320
    #203 0x10d573dba in mrb_check_convert_type object.c:356
    #204 0x10d5985f5 in mrb_str_to_str string.c:1028
    #205 0x10d5abeb6 in mrb_str_append string.c:2605
    #206 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #207 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #208 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #209 0x10d53edb2 in mrb_method_missing kernel.c:926
    #210 0x10d603c18 in mrb_vm_exec vm.c:1229
    #211 0x10d5f9f99 in mrb_vm_run vm.c:820
    #212 0x10d5f301e in mrb_run vm.c:2604
    #213 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #214 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #215 0x10d572c9e in convert_type object.c:320
    #216 0x10d573dba in mrb_check_convert_type object.c:356
    #217 0x10d5985f5 in mrb_str_to_str string.c:1028
    #218 0x10d5abeb6 in mrb_str_append string.c:2605
    #219 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #220 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #221 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #222 0x10d53edb2 in mrb_method_missing kernel.c:926
    #223 0x10d603c18 in mrb_vm_exec vm.c:1229
    #224 0x10d5f9f99 in mrb_vm_run vm.c:820
    #225 0x10d5f301e in mrb_run vm.c:2604
    #226 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #227 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #228 0x10d572c9e in convert_type object.c:320
    #229 0x10d573dba in mrb_check_convert_type object.c:356
    #230 0x10d5985f5 in mrb_str_to_str string.c:1028
    #231 0x10d5abeb6 in mrb_str_append string.c:2605
    #232 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #233 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #234 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #235 0x10d53edb2 in mrb_method_missing kernel.c:926
    #236 0x10d603c18 in mrb_vm_exec vm.c:1229
    #237 0x10d5f9f99 in mrb_vm_run vm.c:820
    #238 0x10d5f301e in mrb_run vm.c:2604
    #239 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #240 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #241 0x10d572c9e in convert_type object.c:320
    #242 0x10d573dba in mrb_check_convert_type object.c:356
    #243 0x10d5985f5 in mrb_str_to_str string.c:1028
    #244 0x10d5abeb6 in mrb_str_append string.c:2605
    #245 0x10d682a7c in mrb_proc_inspect (mruby+0x1001eea7c)
    #246 0x10d5f0565 in mrb_funcall_with_block vm.c:444
    #247 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #248 0x10d53edb2 in mrb_method_missing kernel.c:926
    #249 0x10d603c18 in mrb_vm_exec vm.c:1229
    #250 0x10d5f9f99 in mrb_vm_run vm.c:820
    #251 0x10d5f301e in mrb_run vm.c:2604
    #252 0x10d5f0967 in mrb_funcall_with_block vm.c:451
    #253 0x10d5ed337 in mrb_funcall_argv vm.c:461
    #254 0x10d572c9e in convert_type object.c:320
    #255 0x10d573dba in mrb_check_convert_type object.c:356

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_platform.dylib+0x5f3c) in _platform_memmove$VARIANT$Haswell
==49854==ABORTING
Abort trap: 6
```
The crash occurs in the same place as https://github.com/mruby/mruby/issues/3507 so the two could be related.

This issue was reported by https://hackerone.com/ssarong

**Comment by matz** [comment]
75c374c fixed the issue. See https://github.com/mruby/mruby/issues/3507#issuecomment-287604999
