### ISSUE TITLE
Segfault in OP_CALL

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3516]
The following input to `mirb` demonstrates a crash: [213417.txt](https://github.com/mruby/mruby/files/844947/213417.txt)

(Note that input only crashes mirb, not mruby).

ASAN report:
```
ASAN:DEADLYSIGNAL
=================================================================
==51517==ERROR: AddressSanitizer: SEGV on unknown address 0x000000786630 (pc 0x7fffaf668f3d bp 0x7fff5c557480 sp 0x7fff5c557480 T0)
    #0 0x7fffaf668f3c in _platform_memmove$VARIANT$Haswell (libsystem_platform.dylib+0x5f3c)
    #1 0x103a45bf8 in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib+0x41bf8)
    #2 0x103812cf4 in mrb_vm_exec vm.c:1365
    #3 0x103805969 in mrb_vm_run vm.c:820
    #4 0x1036a0a29 in main mirb.c:549
    #5 0x7fffaf458254 in start (libdyld.dylib+0x5254)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_platform.dylib+0x5f3c) in _platform_memmove$VARIANT$Haswell
==51517==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/ston3

**Comment by clayton-shopify** [comment]
Like #3514 the problem went away after https://github.com/mruby/mruby/commit/6ea26aafd5a2d64987bd1607f9212f6ce494765c. I'm not sure whether that's a coincidence.

**Comment by matz** [comment]
If the configuration use `MRB_GC_FIXED_ARENA`, it's not a coincidence.
