### ISSUE TITLE
Null pointer dereference in OP_GETCONST

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3518]
The following input demonstrates a crash:
```ruby
def a
  b
rescue
ensure
  a
  proc { return }.call
end

begin
  a
rescue
end
```
The debugger shows that `regs` is null in `OP_GETCONST`:
```
* thread #1: tid = 0x6b7ab, 0x00007fffaf668f44 libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 164, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x30)
    frame #0: 0x00007fffaf668f44 libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 164
libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell:
->  0x7fffaf668f44 <+164>: movq   %rcx, (%rdi)
    0x7fffaf668f47 <+167>: movq   %r8, (%rdi,%rdx)
    0x7fffaf668f4b <+171>: popq   %rbp
    0x7fffaf668f4c <+172>: retq
(lldb) frame select 2
frame #2: 0x000000010016a45a mruby`mrb_vm_exec(mrb=0x000061400000fe40, proc=0x000062f000002c50, pc=0x000060600000a418) + 17226 at vm.c:987
   984 	      ERR_PC_SET(mrb, pc);
   985 	      val = mrb_vm_const_get(mrb, syms[GETARG_Bx(i)]);
   986 	      ERR_PC_CLR(mrb);
-> 987 	      regs[GETARG_A(i)] = val;
   988 	      NEXT;
   989 	    }
   990
(lldb) print mrb->c->stack
(mrb_value *) $0 = 0x0000000000000000
```
ASAN report:
```
==52932==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x7fffaf668f44 bp 0x7fff58376ba0 sp 0x7fff58376ba0 T0)
    #0 0x7fffaf668f43 in _platform_memmove$VARIANT$Haswell (libsystem_platform.dylib+0x5f43)
    #1 0x1073eebf8 in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib+0x41bf8)
    #2 0x1071b3459 in mrb_vm_exec vm.c:987
    #3 0x1071aef99 in mrb_vm_run vm.c:820
    #4 0x1071a801e in mrb_run vm.c:2604
    #5 0x1071dea2a in ecall vm.c:312
    #6 0x1071c343a in mrb_vm_exec vm.c:1685
    #7 0x1071aef99 in mrb_vm_run vm.c:820
    #8 0x1071a801e in mrb_run vm.c:2604
    #9 0x1071dea2a in ecall vm.c:312
    #10 0x1071b7771 in mrb_vm_exec vm.c:1166
    #11 0x1071aef99 in mrb_vm_run vm.c:820
    #12 0x1071a801e in mrb_run vm.c:2604
    #13 0x1071dea2a in ecall vm.c:312
    #14 0x1071b7771 in mrb_vm_exec vm.c:1166
    #15 0x1071aef99 in mrb_vm_run vm.c:820
    #16 0x1071a801e in mrb_run vm.c:2604
    #17 0x1071dea2a in ecall vm.c:312
    #18 0x1071b7771 in mrb_vm_exec vm.c:1166
    #19 0x1071aef99 in mrb_vm_run vm.c:820
    #20 0x1071a801e in mrb_run vm.c:2604
    #21 0x1071dea2a in ecall vm.c:312
    #22 0x1071b7771 in mrb_vm_exec vm.c:1166
    #23 0x1071aef99 in mrb_vm_run vm.c:820
    #24 0x1071a801e in mrb_run vm.c:2604
    #25 0x1071dea2a in ecall vm.c:312
    #26 0x1071b7771 in mrb_vm_exec vm.c:1166
    #27 0x1071aef99 in mrb_vm_run vm.c:820
    #28 0x1071a801e in mrb_run vm.c:2604
    #29 0x1071dea2a in ecall vm.c:312
    #30 0x1071b7771 in mrb_vm_exec vm.c:1166
    #31 0x1071aef99 in mrb_vm_run vm.c:820
    #32 0x1071a801e in mrb_run vm.c:2604
    #33 0x1071dea2a in ecall vm.c:312
    #34 0x1071b7771 in mrb_vm_exec vm.c:1166
    #35 0x1071aef99 in mrb_vm_run vm.c:820
    #36 0x1071a801e in mrb_run vm.c:2604
    #37 0x1071dea2a in ecall vm.c:312
    #38 0x1071b7771 in mrb_vm_exec vm.c:1166
    #39 0x1071aef99 in mrb_vm_run vm.c:820
    #40 0x1071a801e in mrb_run vm.c:2604
    #41 0x1071dea2a in ecall vm.c:312
    #42 0x1071b7771 in mrb_vm_exec vm.c:1166
    #43 0x1071aef99 in mrb_vm_run vm.c:820
    #44 0x1071a801e in mrb_run vm.c:2604
    #45 0x1071dea2a in ecall vm.c:312
    #46 0x1071b7771 in mrb_vm_exec vm.c:1166
    #47 0x1071aef99 in mrb_vm_run vm.c:820
    #48 0x1071a801e in mrb_run vm.c:2604
    #49 0x1071dea2a in ecall vm.c:312
    #50 0x1071b7771 in mrb_vm_exec vm.c:1166
    #51 0x1071aef99 in mrb_vm_run vm.c:820
    #52 0x1071a801e in mrb_run vm.c:2604
    #53 0x1071dea2a in ecall vm.c:312
    #54 0x1071b7771 in mrb_vm_exec vm.c:1166
    #55 0x1071aef99 in mrb_vm_run vm.c:820
    #56 0x1071a801e in mrb_run vm.c:2604
    #57 0x1071dea2a in ecall vm.c:312
    #58 0x1071b7771 in mrb_vm_exec vm.c:1166
    #59 0x1071aef99 in mrb_vm_run vm.c:820
    #60 0x1071a801e in mrb_run vm.c:2604
    #61 0x1071dea2a in ecall vm.c:312
    #62 0x1071b7771 in mrb_vm_exec vm.c:1166
    #63 0x1071aef99 in mrb_vm_run vm.c:820
    #64 0x1071a801e in mrb_run vm.c:2604
    #65 0x1071dea2a in ecall vm.c:312
    #66 0x1071b7771 in mrb_vm_exec vm.c:1166
    #67 0x1071aef99 in mrb_vm_run vm.c:820
    #68 0x1071a801e in mrb_run vm.c:2604
    #69 0x1071dea2a in ecall vm.c:312
    #70 0x1071b7771 in mrb_vm_exec vm.c:1166
    #71 0x1071aef99 in mrb_vm_run vm.c:820
    #72 0x1071a801e in mrb_run vm.c:2604
    #73 0x1071dea2a in ecall vm.c:312
    #74 0x1071b7771 in mrb_vm_exec vm.c:1166
    #75 0x1071aef99 in mrb_vm_run vm.c:820
    #76 0x1071a801e in mrb_run vm.c:2604
    #77 0x1071dea2a in ecall vm.c:312
    #78 0x1071b7771 in mrb_vm_exec vm.c:1166
    #79 0x1071aef99 in mrb_vm_run vm.c:820
    #80 0x1071a801e in mrb_run vm.c:2604
    #81 0x1071dea2a in ecall vm.c:312
    #82 0x1071b7771 in mrb_vm_exec vm.c:1166
    #83 0x1071aef99 in mrb_vm_run vm.c:820
    #84 0x1071a801e in mrb_run vm.c:2604
    #85 0x1071dea2a in ecall vm.c:312
    #86 0x1071b7771 in mrb_vm_exec vm.c:1166
    #87 0x1071aef99 in mrb_vm_run vm.c:820
    #88 0x1071a801e in mrb_run vm.c:2604
    #89 0x1071dea2a in ecall vm.c:312
    #90 0x1071b7771 in mrb_vm_exec vm.c:1166
    #91 0x1071aef99 in mrb_vm_run vm.c:820
    #92 0x1071a801e in mrb_run vm.c:2604
    #93 0x1071dea2a in ecall vm.c:312
    #94 0x1071b7771 in mrb_vm_exec vm.c:1166
    #95 0x1071aef99 in mrb_vm_run vm.c:820
    #96 0x1071a801e in mrb_run vm.c:2604
    #97 0x1071dea2a in ecall vm.c:312
    #98 0x1071b7771 in mrb_vm_exec vm.c:1166
    #99 0x1071aef99 in mrb_vm_run vm.c:820
    #100 0x1071a801e in mrb_run vm.c:2604
    #101 0x1071dea2a in ecall vm.c:312
    #102 0x1071b7771 in mrb_vm_exec vm.c:1166
    #103 0x1071aef99 in mrb_vm_run vm.c:820
    #104 0x1071a801e in mrb_run vm.c:2604
    #105 0x1071dea2a in ecall vm.c:312
    #106 0x1071b7771 in mrb_vm_exec vm.c:1166
    #107 0x1071aef99 in mrb_vm_run vm.c:820
    #108 0x1071a801e in mrb_run vm.c:2604
    #109 0x1071dea2a in ecall vm.c:312
    #110 0x1071b7771 in mrb_vm_exec vm.c:1166
    #111 0x1071aef99 in mrb_vm_run vm.c:820
    #112 0x1071a801e in mrb_run vm.c:2604
    #113 0x1071dea2a in ecall vm.c:312
    #114 0x1071b7771 in mrb_vm_exec vm.c:1166
    #115 0x1071aef99 in mrb_vm_run vm.c:820
    #116 0x1071a801e in mrb_run vm.c:2604
    #117 0x1071dea2a in ecall vm.c:312
    #118 0x1071b7771 in mrb_vm_exec vm.c:1166
    #119 0x1071aef99 in mrb_vm_run vm.c:820
    #120 0x1071a801e in mrb_run vm.c:2604
    #121 0x1071dea2a in ecall vm.c:312
    #122 0x1071b7771 in mrb_vm_exec vm.c:1166
    #123 0x1071aef99 in mrb_vm_run vm.c:820
    #124 0x1071a801e in mrb_run vm.c:2604
    #125 0x1071dea2a in ecall vm.c:312
    #126 0x1071b7771 in mrb_vm_exec vm.c:1166
    #127 0x1071aef99 in mrb_vm_run vm.c:820
    #128 0x1071a801e in mrb_run vm.c:2604
    #129 0x1071dea2a in ecall vm.c:312
    #130 0x1071b7771 in mrb_vm_exec vm.c:1166
    #131 0x1071aef99 in mrb_vm_run vm.c:820
    #132 0x1071a801e in mrb_run vm.c:2604
    #133 0x1071dea2a in ecall vm.c:312
    #134 0x1071b7771 in mrb_vm_exec vm.c:1166
    #135 0x1071aef99 in mrb_vm_run vm.c:820
    #136 0x1071a801e in mrb_run vm.c:2604
    #137 0x1071dea2a in ecall vm.c:312
    #138 0x1071b7771 in mrb_vm_exec vm.c:1166
    #139 0x1071aef99 in mrb_vm_run vm.c:820
    #140 0x1071a801e in mrb_run vm.c:2604
    #141 0x1071dea2a in ecall vm.c:312
    #142 0x1071b7771 in mrb_vm_exec vm.c:1166
    #143 0x1071aef99 in mrb_vm_run vm.c:820
    #144 0x1071a801e in mrb_run vm.c:2604
    #145 0x1071dea2a in ecall vm.c:312
    #146 0x1071b7771 in mrb_vm_exec vm.c:1166
    #147 0x1071aef99 in mrb_vm_run vm.c:820
    #148 0x1071a801e in mrb_run vm.c:2604
    #149 0x1071dea2a in ecall vm.c:312
    #150 0x1071b7771 in mrb_vm_exec vm.c:1166
    #151 0x1071aef99 in mrb_vm_run vm.c:820
    #152 0x1071a801e in mrb_run vm.c:2604
    #153 0x1071dea2a in ecall vm.c:312
    #154 0x1071b7771 in mrb_vm_exec vm.c:1166
    #155 0x1071aef99 in mrb_vm_run vm.c:820
    #156 0x1071a801e in mrb_run vm.c:2604
    #157 0x1071dea2a in ecall vm.c:312
    #158 0x1071b7771 in mrb_vm_exec vm.c:1166
    #159 0x1071aef99 in mrb_vm_run vm.c:820
    #160 0x1071a801e in mrb_run vm.c:2604
    #161 0x1071dea2a in ecall vm.c:312
    #162 0x1071b7771 in mrb_vm_exec vm.c:1166
    #163 0x1071aef99 in mrb_vm_run vm.c:820
    #164 0x1071a801e in mrb_run vm.c:2604
    #165 0x1071dea2a in ecall vm.c:312
    #166 0x1071b7771 in mrb_vm_exec vm.c:1166
    #167 0x1071aef99 in mrb_vm_run vm.c:820
    #168 0x1071a801e in mrb_run vm.c:2604
    #169 0x1071dea2a in ecall vm.c:312
    #170 0x1071b7771 in mrb_vm_exec vm.c:1166
    #171 0x1071aef99 in mrb_vm_run vm.c:820
    #172 0x1071a801e in mrb_run vm.c:2604
    #173 0x1071dea2a in ecall vm.c:312
    #174 0x1071b7771 in mrb_vm_exec vm.c:1166
    #175 0x1071aef99 in mrb_vm_run vm.c:820
    #176 0x1071a801e in mrb_run vm.c:2604
    #177 0x1071dea2a in ecall vm.c:312
    #178 0x1071b7771 in mrb_vm_exec vm.c:1166
    #179 0x1071aef99 in mrb_vm_run vm.c:820
    #180 0x1071a801e in mrb_run vm.c:2604
    #181 0x1071dea2a in ecall vm.c:312
    #182 0x1071b7771 in mrb_vm_exec vm.c:1166
    #183 0x1071aef99 in mrb_vm_run vm.c:820
    #184 0x1071a801e in mrb_run vm.c:2604
    #185 0x1071dea2a in ecall vm.c:312
    #186 0x1071b7771 in mrb_vm_exec vm.c:1166
    #187 0x1071aef99 in mrb_vm_run vm.c:820
    #188 0x1071a801e in mrb_run vm.c:2604
    #189 0x1071dea2a in ecall vm.c:312
    #190 0x1071b7771 in mrb_vm_exec vm.c:1166
    #191 0x1071aef99 in mrb_vm_run vm.c:820
    #192 0x1071a801e in mrb_run vm.c:2604
    #193 0x1071dea2a in ecall vm.c:312
    #194 0x1071b7771 in mrb_vm_exec vm.c:1166
    #195 0x1071aef99 in mrb_vm_run vm.c:820
    #196 0x1071a801e in mrb_run vm.c:2604
    #197 0x1071dea2a in ecall vm.c:312
    #198 0x1071b7771 in mrb_vm_exec vm.c:1166
    #199 0x1071aef99 in mrb_vm_run vm.c:820
    #200 0x1071a801e in mrb_run vm.c:2604
    #201 0x1071dea2a in ecall vm.c:312
    #202 0x1071b7771 in mrb_vm_exec vm.c:1166
    #203 0x1071aef99 in mrb_vm_run vm.c:820
    #204 0x1071a801e in mrb_run vm.c:2604
    #205 0x1071dea2a in ecall vm.c:312
    #206 0x1071b7771 in mrb_vm_exec vm.c:1166
    #207 0x1071aef99 in mrb_vm_run vm.c:820
    #208 0x1071a801e in mrb_run vm.c:2604
    #209 0x1071dea2a in ecall vm.c:312
    #210 0x1071b7771 in mrb_vm_exec vm.c:1166
    #211 0x1071aef99 in mrb_vm_run vm.c:820
    #212 0x1071a801e in mrb_run vm.c:2604
    #213 0x1071dea2a in ecall vm.c:312
    #214 0x1071b7771 in mrb_vm_exec vm.c:1166
    #215 0x1071aef99 in mrb_vm_run vm.c:820
    #216 0x1071a801e in mrb_run vm.c:2604
    #217 0x1071dea2a in ecall vm.c:312
    #218 0x1071b7771 in mrb_vm_exec vm.c:1166
    #219 0x1071aef99 in mrb_vm_run vm.c:820
    #220 0x1071a801e in mrb_run vm.c:2604
    #221 0x1071dea2a in ecall vm.c:312
    #222 0x1071b7771 in mrb_vm_exec vm.c:1166
    #223 0x1071aef99 in mrb_vm_run vm.c:820
    #224 0x1071a801e in mrb_run vm.c:2604
    #225 0x1071dea2a in ecall vm.c:312
    #226 0x1071b7771 in mrb_vm_exec vm.c:1166
    #227 0x1071aef99 in mrb_vm_run vm.c:820
    #228 0x1071a801e in mrb_run vm.c:2604
    #229 0x1071dea2a in ecall vm.c:312
    #230 0x1071b7771 in mrb_vm_exec vm.c:1166
    #231 0x1071aef99 in mrb_vm_run vm.c:820
    #232 0x1071a801e in mrb_run vm.c:2604
    #233 0x1071dea2a in ecall vm.c:312
    #234 0x1071b7771 in mrb_vm_exec vm.c:1166
    #235 0x1071aef99 in mrb_vm_run vm.c:820
    #236 0x1071a801e in mrb_run vm.c:2604
    #237 0x1071dea2a in ecall vm.c:312
    #238 0x1071b7771 in mrb_vm_exec vm.c:1166
    #239 0x1071aef99 in mrb_vm_run vm.c:820
    #240 0x1071a801e in mrb_run vm.c:2604
    #241 0x1071dea2a in ecall vm.c:312
    #242 0x1071b7771 in mrb_vm_exec vm.c:1166
    #243 0x1071aef99 in mrb_vm_run vm.c:820
    #244 0x1071a801e in mrb_run vm.c:2604
    #245 0x1071dea2a in ecall vm.c:312
    #246 0x1071b7771 in mrb_vm_exec vm.c:1166
    #247 0x1071aef99 in mrb_vm_run vm.c:820
    #248 0x1071a801e in mrb_run vm.c:2604
    #249 0x1071dea2a in ecall vm.c:312
    #250 0x1071b7771 in mrb_vm_exec vm.c:1166
    #251 0x1071aef99 in mrb_vm_run vm.c:820
    #252 0x1071a801e in mrb_run vm.c:2604
    #253 0x1071dea2a in ecall vm.c:312
    #254 0x1071b7771 in mrb_vm_exec vm.c:1166
    #255 0x1071aef99 in mrb_vm_run vm.c:820

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_platform.dylib+0x5f43) in _platform_memmove$VARIANT$Haswell
==52932==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/ssarong

**Comment by matz** [comment]
75c374 solved the issue.
