### ISSUE TITLE
Null pointer dereference in mrb_gc_mark

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3555]
The following input to mruby demonstrates a crash: [215761.txt](https://github.com/mruby/mruby/files/875863/215761.txt)

Note that I was only able to reproduce the crash using gcc on Ubuntu (and not with clang on OS X).

gdb output:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004036e2 in mrb_gc_mark (mrb=0x6b0010, obj=0x10) at /home/clayton/git/mruby/src/gc.c:697
697	  if (!is_white(obj)) return;

(gdb) print obj
$1 = (struct RBasic *) 0x10

(gdb) bt
#0  0x00000000004036e2 in mrb_gc_mark (mrb=0x6b0010, obj=0x10) at /home/clayton/git/mruby/src/gc.c:697
#1  0x0000000000403415 in gc_mark_children (mrb=0x6b0010, gc=0x6b00e8, obj=0x743a40)
    at /home/clayton/git/mruby/src/gc.c:600
#2  0x0000000000404061 in gc_mark_gray_list (mrb=0x6b0010, gc=0x6b00e8) at /home/clayton/git/mruby/src/gc.c:970
#3  0x000000000040411a in final_marking_phase (mrb=0x6b0010, gc=0x6b00e8) at /home/clayton/git/mruby/src/gc.c:993
#4  0x0000000000404519 in incremental_gc (mrb=0x6b0010, gc=0x6b00e8, limit=2000)
    at /home/clayton/git/mruby/src/gc.c:1090
#5  0x0000000000404613 in incremental_gc_step (mrb=0x6b0010, gc=0x6b00e8) at /home/clayton/git/mruby/src/gc.c:1122
#6  0x00000000004047b9 in mrb_incremental_gc (mrb=0x6b0010) at /home/clayton/git/mruby/src/gc.c:1166
#7  0x000000000040302e in mrb_obj_alloc (mrb=0x6b0010, ttype=MRB_TT_STRING, cls=0x6ba510)
    at /home/clayton/git/mruby/src/gc.c:507
#8  0x0000000000413d57 in str_new (mrb=0x6b0010, p=0x711150 "215761.rb", len=9)
    at /home/clayton/git/mruby/src/string.c:59
#9  0x000000000041453e in mrb_str_new_cstr (mrb=0x6b0010, p=0x711150 "215761.rb")
    at /home/clayton/git/mruby/src/string.c:215
#10 0x000000000041c23a in mrb_restore_backtrace (mrb=0x6b0010) at /home/clayton/git/mruby/src/backtrace.c:407
#11 0x000000000042f1fe in mrb_exc_set (mrb=0x6b0010, exc=...) at /home/clayton/git/mruby/src/error.c:282
#12 0x000000000042f2ea in mrb_exc_raise (mrb=0x6b0010, exc=...) at /home/clayton/git/mruby/src/error.c:303
#13 0x0000000000408b82 in mrb_funcall_with_block (mrb=0x6b0010, self=..., mid=52, argc=1, argv=0x7ffffff3c5b0,
    blk=...) at /home/clayton/git/mruby/src/vm.c:395
#14 0x00000000004090af in mrb_funcall_argv (mrb=0x6b0010, self=..., mid=52, argc=1, argv=0x7ffffff3c5b0)
    at /home/clayton/git/mruby/src/vm.c:461
#15 0x000000000042c45a in const_get (mrb=0x6b0010, base=0x6bc4c0, sym=678)
    at /home/clayton/git/mruby/src/variable.c:913
#16 0x000000000042c608 in mrb_vm_const_get (mrb=0x6b0010, sym=678) at /home/clayton/git/mruby/src/variable.c:953
#17 0x000000000040a895 in mrb_vm_exec (mrb=0x6b0010, proc=0x73afc0, pc=0x725c00)
    at /home/clayton/git/mruby/src/vm.c:988
#18 0x0000000000409eec in mrb_vm_run (mrb=0x6b0010, proc=0x73afc0, self=..., stack_keep=2)
    at /home/clayton/git/mruby/src/vm.c:823
#19 0x0000000000412281 in mrb_run (mrb=0x6b0010, proc=0x73afc0, self=...) at /home/clayton/git/mruby/src/vm.c:2603
#20 0x0000000000408566 in ecall (mrb=0x6b0010, i=255) at /home/clayton/git/mruby/src/vm.c:312
#21 0x000000000040d8e9 in mrb_vm_exec (mrb=0x6b0010, proc=0x6b21a0, pc=0x71f308)
    at /home/clayton/git/mruby/src/vm.c:1682
#22 0x0000000000409eec in mrb_vm_run (mrb=0x6b0010, proc=0x6b21a0, self=..., stack_keep=2)
    ...
```
This issue was reported by https://hackerone.com/ssarong

**Comment by matz** [comment]
I couldn't reproduce the problem. Hopefully fixed.

**Comment by clayton-shopify** [comment]
Yes, it stopped crashing after https://github.com/mruby/mruby/commit/ab25eaea2345577b4e28672908f0190ce6b21684.
