### ISSUE TITLE
Null pointer dereference in join_ary

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3586]
The following input to mirb demonstrates a crash:
```ruby
(0*0).t{}
Fiber.new{0[]}.resume
r=y=(0..10000).to_a
l=s=u=e=o=o.to_enum
o.to_enum
```
(Note that this input must be given to mirb, not mruby.)

ASAN report:
```
==62648==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fffbbdccf3d bp 0x7fff5fa5f540 sp 0x7fff5fa5f540 T0)
==62648==The signal is caused by a READ memory access.
==62648==Hint: address points to the zero page.
    #0 0x7fffbbdccf3c in _platform_memmove$VARIANT$Haswell (libsystem_platform.dylib:x86_64+0x5f3c)
    #1 0x10059d504 in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4d504)
    #2 0x1001a22c7 in join_ary array.c:1043
    #3 0x1001a2525 in join_ary array.c:1047
    #4 0x1001a12d2 in mrb_ary_join array.c:1084
    #5 0x1001fbe42 in mrb_vformat (mirb:x86_64+0x10006ae42)
    #6 0x1001fc861 in raise_va (mirb:x86_64+0x10006b861)
    #7 0x1001fc6d4 in mrb_raisef (mirb:x86_64+0x10006b6d4)
    #8 0x100270833 in mrb_convert_type (mirb:x86_64+0x1000df833)
    #9 0x100295901 in mrb_str_to_str (mirb:x86_64+0x100104901)
    #10 0x100294288 in mrb_str_concat (mirb:x86_64+0x100103288)
    #11 0x10032011c in mrb_vm_exec (mirb:x86_64+0x10018f11c)
    #12 0x1002f7919 in mrb_vm_run (mirb:x86_64+0x100166919)
    #13 0x1002f05de in mrb_run (mirb:x86_64+0x10015f5de)
    #14 0x1002edf27 in mrb_funcall_with_block (mirb:x86_64+0x10015cf27)
    #15 0x1002eb117 in mrb_funcall_with_block (mirb:x86_64+0x10015a117)
    #16 0x1002ea8f7 in mrb_funcall_argv (mirb:x86_64+0x1001598f7)
    #17 0x1002ea36e in mrb_funcall (mirb:x86_64+0x10015936e)
    #18 0x10019511b in p mirb.c:92
    #19 0x100193ab4 in main mirb.c:564
    #20 0x7fffbbbba234 in start (libdyld.dylib:x86_64+0x5234)

==62648==Register values:
rax = 0x00007fff5fa5fe60  rbx = 0x00000001013174c0  rcx = 0x0000000000000000  rdx = 0x0000000000000008
rdi = 0x00007fff5fa5fe60  rsi = 0x0000000000000000  rbp = 0x00007fff5fa5f540  rsp = 0x00007fff5fa5f540
 r8 = 0x00007fff00000010   r9 = 0x0000000000000000  r10 = 0x0000000000000080  r11 = 0x00007fff5fa5fe60
r12 = 0x00007fff5fa5fea0  r13 = 0x0000000000000000  r14 = 0x0000000000000010  r15 = 0x00007fff5fa5fe60
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_platform.dylib:x86_64+0x5f3c) in _platform_memmove$VARIANT$Haswell
==62648==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/ston3

**Comment by clayton-shopify** [comment]
This was resolved in https://github.com/mruby/mruby/commit/60d20e1848c4049d725e482a0288eba4e7cc9304.
