### ISSUE TITLE
Invalid memory access in gc_mark_children

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3634]
The following input demonstrates a crash:
```ruby
def x
    ensure
    x
end

x
```
ASAN report:
```
==25455==ERROR: AddressSanitizer: SEGV on unknown address 0x629fffff5a98 (pc 0x00010eb5627f bp 0x7fff509c9660 sp 0x7fff509c9400 T0)
    #0 0x10eb5627e in gc_mark_children gc.c:655
    #1 0x10eb552ff in gc_gray_mark gc.c:896
    #2 0x10eb534e6 in incremental_marking_phase gc.c:991
    #3 0x10eb52653 in incremental_gc gc.c:1095
    #4 0x10eb4e64c in incremental_gc_step gc.c:1130
    #5 0x10eb4d85c in mrb_incremental_gc gc.c:1174
    #6 0x10eb4d1c8 in mrb_obj_alloc gc.c:508
    #7 0x10ebb7952 in env_new (mruby:x86_64+0x1000eb952)
    #8 0x10ebb70db in closure_setup (mruby:x86_64+0x1000eb0db)
    #9 0x10ebb6ff7 in mrb_closure_new (mruby:x86_64+0x1000eaff7)
    #10 0x10ec3b3fd in mrb_vm_exec (mruby:x86_64+0x10016f3fd)
    #11 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #12 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #13 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #14 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #15 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #16 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #17 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #18 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #19 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #20 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #21 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #22 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #23 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #24 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #25 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #26 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #27 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #28 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #29 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #30 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #31 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #32 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #33 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #34 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #35 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #36 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #37 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #38 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #39 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #40 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #41 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #42 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #43 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #44 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #45 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #46 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #47 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #48 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #49 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #50 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #51 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #52 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #53 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #54 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #55 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #56 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #57 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #58 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #59 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #60 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #61 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #62 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #63 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #64 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #65 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #66 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #67 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #68 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #69 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #70 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #71 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #72 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #73 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #74 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #75 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #76 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #77 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #78 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #79 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #80 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #81 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #82 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #83 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #84 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #85 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #86 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #87 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #88 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #89 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #90 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #91 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #92 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #93 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #94 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #95 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #96 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #97 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #98 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #99 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #100 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #101 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #102 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #103 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #104 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #105 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #106 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #107 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #108 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #109 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #110 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #111 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #112 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #113 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #114 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #115 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #116 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #117 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #118 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #119 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #120 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #121 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #122 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #123 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #124 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #125 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #126 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #127 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #128 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #129 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #130 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #131 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #132 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #133 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #134 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #135 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #136 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #137 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #138 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #139 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #140 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #141 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #142 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #143 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #144 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #145 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #146 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #147 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #148 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #149 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #150 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #151 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #152 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #153 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #154 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #155 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #156 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #157 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #158 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #159 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #160 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #161 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #162 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #163 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #164 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #165 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #166 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #167 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #168 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #169 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #170 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #171 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #172 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #173 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #174 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #175 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #176 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #177 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #178 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #179 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #180 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #181 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #182 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #183 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #184 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #185 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #186 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #187 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #188 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #189 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #190 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #191 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #192 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #193 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #194 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #195 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #196 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #197 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #198 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #199 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #200 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #201 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #202 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #203 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #204 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #205 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #206 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #207 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #208 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #209 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #210 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #211 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #212 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #213 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #214 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #215 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #216 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #217 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #218 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #219 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #220 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #221 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #222 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #223 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #224 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #225 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #226 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #227 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #228 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #229 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #230 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #231 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #232 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #233 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #234 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #235 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #236 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #237 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #238 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #239 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #240 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #241 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #242 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #243 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #244 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #245 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #246 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #247 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #248 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #249 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #250 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #251 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)
    #252 0x10ec2ba1e in mrb_run (mruby:x86_64+0x10015fa1e)
    #253 0x10ec64b9a in ecall (mruby:x86_64+0x100198b9a)
    #254 0x10ec3c230 in mrb_vm_exec (mruby:x86_64+0x100170230)
    #255 0x10ec33acf in mrb_vm_run (mruby:x86_64+0x100167acf)

==25455==Register values:
rax = 0x0000629fffff5a98  rbx = 0x00007fff509c9ac0  rcx = 0x000062f000015e28  rdx = 0x00001c53ffffeb53
rdi = 0x000061400000a400  rsi = 0x0000100000000000  rbp = 0x00007fff509c9660  rsp = 0x00007fff509c9400
 r8 = 0x0000100000000000   r9 = 0x00007fff509c9280  r10 = 0x00007fff509c92a0  r11 = 0xffffe290af63ff90
r12 = 0xf2f20000f1f1f1f1  r13 = 0x00001fffea13a1e8  r14 = 0xf2f20000f2f2f2f2  r15 = 0xf2f2f2f2f2040000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV gc.c:655 in gc_mark_children
==25455==ABORTING
Abort trap: 6
```
This issue was reported by Dinko Galetic & Denis Kasak (https://hackerone.com/dgaletic).

**Comment by clayton-shopify** [comment]
This one also seems to be the same issue as https://github.com/mruby/mruby/issues/3549#issuecomment-296678105 and #3633.
