### ISSUE TITLE
Null pointer dereference in mrb_class

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3670]
The following input demonstrates a crash, when supplied to mirb:
```ruby
b = []
c = 0

class A < Fiber
end

x = A.new {a}.resume
y = A.new {a}.resume
m = A.new {}.resume

d = b.to_s
Array.new {}

begin
    break
    n = A.new {}
    z = A.new {}
    ensure
    z.resume
end
```
ASAN report:
```
==71334==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0001064e481a bp 0x7fff59864130 sp 0x7fff59863fc0 T0)
==71334==The signal is caused by a READ memory access.
==71334==Hint: address points to the zero page.
    #0 0x1064e4819 in mrb_class class.h:50
    #1 0x1064f79b3 in mrb_vm_exec vm.c:1269
    #2 0x1064eda5f in mrb_vm_run vm.c:860
    #3 0x1064e59ae in mrb_run vm.c:2738
    #4 0x10651eca3 in ecall vm.c:326
    #5 0x106503036 in mrb_vm_exec vm.c:1789
    #6 0x1064eda5f in mrb_vm_run vm.c:860
    #7 0x10638b6f9 in main mirb.c:549
    #8 0x7fff8c15e234 in start (libdyld.dylib:x86_64+0x5234)

==71334==Register values:
rax = 0x00007fff59863fe0  rbx = 0x00007fff59864000  rcx = 0x7b206164626d6174  rdx = 0x0f641c2c8c4dac2e
rdi = 0x00001fffeb30c7fd  rsi = 0x0000100000000000  rbp = 0x00007fff59864130  rsp = 0x00007fff59863fc0
 r8 = 0x0000100000000000   r9 = 0x73dc72c87c940000  r10 = 0xf2f20000f2f20000  r11 = 0x00001e2f5984dde0
r12 = 0xf2f20000f1f1f1f1  r13 = 0x00001fffeb30d63c  r14 = 0xf2f20000f2f2f2f2  r15 = 0xf2f2f2f2f2040000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV class.h:50 in mrb_class
==71334==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/ahihi

**Comment by matz** [comment]
I think 34dd258c fixed this too.
