### ISSUE TITLE
Null pointer dereference in kh_get_mt

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3691]
The following input causes a crash, when supplied to mirb:
```ruby
b = Array.new(1, Hash.new)
q = g =  GC.interval_ratio= 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0  
GC.start
p.join

x{}
z = q.join[0] 
q = Class.new{}
i = Struct.new.prepend_features {}	


a = Time.new p = g.initialize

r = b.to_r 
x
m = q.dup  

x
x { }
x	
		
x = b.remove_const x
Array.to_s 
m.inspect 
```
ASAN report:
```
ASAN:DEADLYSIGNAL
=================================================================
==56453==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004 (pc 0x00010036763f bp 0x7fff5f8b3570 sp 0x7fff5f8b3490 T0)
==56453==The signal is caused by a READ memory access.
==56453==Hint: address points to the zero page.
    #0 0x10036763e in kh_get_mt (mirb:x86_64+0x10002563e)
    #1 0x10037fb61 in mrb_method_search_vm (mirb:x86_64+0x10003db61)
    #2 0x1004b0d53 in mrb_vm_exec (mirb:x86_64+0x10016ed53)
    #3 0x1004a6cb6 in mrb_vm_run (mirb:x86_64+0x100164cb6)
    #4 0x100344a09 in main mirb.c:549
    #5 0x7fffe5638234 in start (libdyld.dylib:x86_64+0x5234)

==56453==Register values:
rax = 0x0000000000000004  rbx = 0xf2f20000f2f2f200  rcx = 0x0000100000000000  rdx = 0x000000000000008d
rdi = 0x0000100000000000  rsi = 0x0000000000000004  rbp = 0x00007fff5f8b3570  rsp = 0x00007fff5f8b3490
 r8 = 0x0000100000000000   r9 = 0x5f15d63889200000  r10 = 0x0000f204f2f20000  r11 = 0x00001e2f5f89deb0
r12 = 0xf2f2f2f2f2040000  r13 = 0xf2f20000f1f1f1f1  r14 = 0xf2f2f200f2f20000  r15 = 0xf2f20000f2f2f2f2
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (mirb:x86_64+0x10002563e) in kh_get_mt
==56453==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/ahihi

**Comment by matz** [comment]
It seems to be fixed, probably by b32ad13
