### ISSUE TITLE
Invalid memory access in mrb_vm_const_get

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3782]
The following input demonstrates a crash when supplied to mirb:
```ruby
1000.times { [0].zip [0] }
(0..1000).to_a
ObjectSpace.each_object{ |obj| obj[] rescue 0 }
```
Note that this only causes a crash in mirb, not in mruby.

ASAN report:
```
ASAN:DEADLYSIGNAL
=================================================================
==93922==ERROR: AddressSanitizer: SEGV on unknown address 0x00000036309c (pc 0x00010b32a37b bp 0x7fff54a16010 sp 0x7fff54a15cc0 T0)
==93922==The signal is caused by a READ memory access.
    #0 0x10b32a37a in mrb_vm_const_get (mirb:x86_64+0x10015437a)
    #1 0x10b3458fb in mrb_vm_exec (mirb:x86_64+0x10016f8fb)
    #2 0x10b341151 in mrb_vm_run (mirb:x86_64+0x10016b151)
    #3 0x10b33889e in mrb_run (mirb:x86_64+0x10016289e)
    #4 0x10b33e813 in mrb_yield_with_class (mirb:x86_64+0x100168813)
    #5 0x10b33f4f8 in mrb_yield (mirb:x86_64+0x1001694f8)
    #6 0x10b3f2a4f in os_each_object_cb mruby_objectspace.c:140
    #7 0x10b25c438 in gc_each_objects gc.c:1493
    #8 0x10b25c170 in mrb_objspace_each_objects gc.c:1515
    #9 0x10b3f1806 in os_each_object mruby_objectspace.c:172
    #10 0x10b34c612 in mrb_vm_exec (mirb:x86_64+0x100176612)
    #11 0x10b341151 in mrb_vm_run (mirb:x86_64+0x10016b151)
    #12 0x10b1d8549 in main mirb.c:549
    #13 0x7fffa6e81234 in start (libdyld.dylib:x86_64+0x5234)

==93922==Register values:
rax = 0x000000000036309c  rbx = 0x00007fff54a15d60  rcx = 0x000000000036309c  rdx = 0x000010000006c613
rdi = 0x0000100000000000  rsi = 0x0000100000000000  rbp = 0x00007fff54a16010  rsp = 0x00007fff54a15cc0
 r8 = 0x00007fff54a15ce0   r9 = 0x00007fff54a15d00  r10 = 0x00007fff54a15d20  r11 = 0x00007fff54a15d40
r12 = 0xf2f20000f1f1f1f1  r13 = 0x00001fffea943a6c  r14 = 0x0000000000000270  r15 = 0x0000100000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (mirb:x86_64+0x10015437a) in mrb_vm_const_get
==93922==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/flamezzz

**Comment by clayton-shopify** [comment]
This issue was submitted by Dinko Galetic & Denis Kasak (https://hackerone.com/dgaletic) found this input, which produces the same crash but in mruby instead of mirb:
```ruby
1.times {}
688.times { [0].zip [0] }
169.times { [0].zip  }
ObjectSpace.each_object{|obj| obj[] rescue 0}
```
A bisect suggests that the problem may have been introduced in da24af34b9c46120376fdf3e42dd5c9949fecd5c.

This ASAN report may be more useful, as it includes line numbers:
```
ASAN:DEADLYSIGNAL
=================================================================
==10212==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000068 (pc 0x00010826784b bp 0x7fff57ad88d0 sp 0x7fff57ad8580 T0)
==10212==The signal is caused by a READ memory access.
==10212==Hint: address points to the zero page.
    #0 0x10826784a in mrb_vm_const_get variable.c:864
    #1 0x108282dcb in mrb_vm_exec vm.c:1114
    #2 0x10827e621 in mrb_vm_run vm.c:904
    #3 0x108275d6e in mrb_run vm.c:2850
    #4 0x10827bce3 in mrb_yield_with_class vm.c:723
    #5 0x10827c9c8 in mrb_yield vm.c:743
    #6 0x10832ff1f in os_each_object_cb mruby_objectspace.c:140
    #7 0x108199908 in gc_each_objects gc.c:1493
    #8 0x108199640 in mrb_objspace_each_objects gc.c:1515
    #9 0x10832ecd6 in os_each_object mruby_objectspace.c:172
    #10 0x108289ae2 in mrb_vm_exec vm.c:1392
    #11 0x10827e621 in mrb_vm_run vm.c:904
    #12 0x1082b42bf in mrb_top_run vm.c:2865
    #13 0x108396b98 in mrb_load_exec parse.y:5822
    #14 0x1083979c5 in mrb_load_file_cxt parse.y:5831
    #15 0x1081168f3 in main mruby.c:227
    #16 0x7fffa6e81234 in start (libdyld.dylib:x86_64+0x5234)

==10212==Register values:
rax = 0x0000000000000068  rbx = 0x00007fff57ad8620  rcx = 0x0000000000000068  rdx = 0x000010000000000d
rdi = 0x0000100000000000  rsi = 0x0000100000000000  rbp = 0x00007fff57ad88d0  rsp = 0x00007fff57ad8580
 r8 = 0x00007fff57ad85a0   r9 = 0x00007fff57ad85c0  r10 = 0x00007fff57ad85e0  r11 = 0x00007fff57ad8600
r12 = 0xf2f20000f1f1f1f1  r13 = 0x00001fffeaf5bf84  r14 = 0x0000000000000270  r15 = 0x0000100000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV variable.c:864 in mrb_vm_const_get
==10212==ABORTING
Abort trap: 6
```
