### ISSUE TITLE
Null pointer dereference in OP_GETCONST

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3803]
The following input demonstrates a crash:
```ruby
def method_missing(*)
proc{}
end

ObjectSpace.each_object{|a = 1;obj|[ObjectSpace.each_object{1&a.initialize_copy(a.length)|obj| obj}] rescue a = nil;class << a;def self.b;6;end;end;0}
```
ASAN report:
```
ASAN:DEADLYSIGNAL
=================================================================
==60052==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x00010985b54c bp 0x7fff56509810 sp 0x7fff56501740 T0)
==60052==The signal is caused by a READ memory access.
==60052==Hint: address points to the zero page.
    #0 0x10985b54b in mrb_vm_exec vm.c:1111
    #1 0x109856ea1 in mrb_vm_run vm.c:904
    #2 0x10984e5ee in mrb_run vm.c:2855
    #3 0x109854563 in mrb_yield_with_class vm.c:723
    #4 0x109855248 in mrb_yield vm.c:743
    #5 0x109908b1f in os_each_object_cb mruby_objectspace.c:140
    #6 0x1097713e1 in gc_each_objects gc.c:1495
    #7 0x109771110 in mrb_objspace_each_objects gc.c:1517
    #8 0x1099078d6 in os_each_object mruby_objectspace.c:172
    #9 0x10986242e in mrb_vm_exec vm.c:1394
    #10 0x109856ea1 in mrb_vm_run vm.c:904
    #11 0x10988cd6f in mrb_top_run vm.c:2870
    #12 0x10996f6f5 in mrb_load_exec parse.y:5831
    #13 0x109970515 in mrb_load_file_cxt parse.y:5840
    #14 0x1096ed983 in main mruby.c:227
    #15 0x7fffa6e81234 in start (libdyld.dylib:x86_64+0x5234)

==60052==Register values:
rax = 0x0000000000000008  rbx = 0xf2f20000f2f2f200  rcx = 0x0000000000000008  rdx = 0x0000100000000001
rdi = 0x0000100000000000  rsi = 0x0000100000000000  rbp = 0x00007fff56509810  rsp = 0x00007fff56501740
 r8 = 0x0000000000000012   r9 = 0x0000100000000000  r10 = 0x000000000000002e  r11 = 0xffffe1d0a9b13fd0
r12 = 0xf2f20000f1f1f1f1  r13 = 0x00001fffeaca1158  r14 = 0xf2f20000f2f2f2f2  r15 = 0xf2f2f2f2f2040000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV vm.c:1111 in mrb_vm_exec
==60052==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/flamezzz

**Comment by matz** [comment]
By the way. I strongly recommend disabling `mruby-objectspace` gem when you try to construct sandbox environment for untrusted code. It opens a huge possibility of vulnerabilities (like this one), with virtually no benefit.

**Comment by clayton-shopify** [comment]
@matz We don't include `mruby-objectspace` in our sandbox. But we do accept bug bounty reports for all of mruby. Payouts are lower for the parts that are not in our sandbox.

**Comment by matz** [comment]
Makes sense.
