### ISSUE TITLE
Segfault in gc_protect

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3869]
The following produces a segfault on Linux:
```
echo 'def class;undef`rescue$0<@f;unde1+1 [1.2]=@f;eUdef?rescue$0 [9.2]<@f;ensure;d ris?rescue$0 [9.2]<@U;end;[].map.R' > aaaaaaaaaa
ulimit -c unlimited
ulimit -v 100000
bin/mruby aaaaaaaaaa
```
The problem only occurs if the script's filename is 10 characters or longer.

Stack trace:
```
#0  0x00000000004030af in gc_protect (mrb=0x8c6010, gc=0x8c60d8, p=0x6098d70) at /home/vagrant/git/mruby/src/gc.c:421
#1  0x00000000004035b5 in mrb_obj_alloc (mrb=0x8c6010, ttype=MRB_TT_DATA, cls=0x0) at /home/vagrant/git/mruby/src/gc.c:529
#2  0x00000000004156ca in mrb_data_object_alloc (mrb=0x8c6010, klass=0x0, ptr=0x54b4680, type=0x4745d0 <bt_type>) at /home/vagrant/git/mruby/src/etc.c:19
#3  0x0000000000407d47 in packed_backtrace (mrb=0x8c6010) at /home/vagrant/git/mruby/src/backtrace.c:209
#4  0x0000000000407e10 in mrb_keep_backtrace (mrb=0x8c6010, exc=...) at /home/vagrant/git/mruby/src/backtrace.c:224
#5  0x00000000004190cb in mrb_exc_set (mrb=0x8c6010, exc=...) at /home/vagrant/git/mruby/src/error.c:237
#6  0x000000000041914c in mrb_exc_raise (mrb=0x8c6010, exc=...) at /home/vagrant/git/mruby/src/error.c:248
#7  0x0000000000419f64 in mrb_no_method_error (mrb=0x8c6010, id=706, args=..., fmt=0x476889 "undefined method '%S' for %S") at /home/vagrant/git/mruby/src/error.c:482
#8  0x0000000000425177 in mrb_method_missing (mrb=0x8c6010, name=706, self=..., args=...) at /home/vagrant/git/mruby/src/kernel.c:977
#9  0x000000000040dbd3 in mrb_vm_exec (mrb=0x8c6010, proc=0x60984d0, pc=0x9363ac) at /home/vagrant/git/mruby/src/vm.c:1420
#10 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x60984d0, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#11 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x60984d0, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#12 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#13 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301d0) at /home/vagrant/git/mruby/src/vm.c:1925
#14 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x6098fb0, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#15 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x6098fb0, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#16 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#17 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301d0) at /home/vagrant/git/mruby/src/vm.c:1925
#18 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x6098d10, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#19 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x6098d10, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#20 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#21 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301d0) at /home/vagrant/git/mruby/src/vm.c:1925
#22 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x609bf80, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#23 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x609bf80, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#24 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#25 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301d0) at /home/vagrant/git/mruby/src/vm.c:1925
#26 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x60a1590, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#27 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x60a1590, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#28 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#29 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301d0) at /home/vagrant/git/mruby/src/vm.c:1925
#30 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x5eb21a0, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#31 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x5eb21a0, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#32 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#33 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301d0) at /home/vagrant/git/mruby/src/vm.c:1925
#34 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x5863980, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#35 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x5863980, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#36 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#37 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301d0) at /home/vagrant/git/mruby/src/vm.c:1925
#38 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x40b8210, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#39 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x40b8210, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#40 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#41 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301d0) at /home/vagrant/git/mruby/src/vm.c:1925
#42 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0xa97e70, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#43 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0xa97e70, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#44 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#45 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301d0) at /home/vagrant/git/mruby/src/vm.c:1925
#46 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x8c90f0, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#47 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x8c90f0, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#48 0x0000000000409bfe in ecall (mrb=0x8c6010) at /home/vagrant/git/mruby/src/vm.c:350
#49 0x0000000000410396 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92a0, pc=0x9301dc) at /home/vagrant/git/mruby/src/vm.c:1925
#50 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x8c9ed0, self=..., stack_keep=2) at /home/vagrant/git/mruby/src/vm.c:930
#51 0x0000000000415472 in mrb_run (mrb=0x8c6010, proc=0x8c9ed0, self=...) at /home/vagrant/git/mruby/src/vm.c:2950
#52 0x000000000040a71f in mrb_funcall_with_block (mrb=0x8c6010, self=..., mid=43, argc=0, argv=0x0, blk=...) at /home/vagrant/git/mruby/src/vm.c:488
#53 0x000000000040a7be in mrb_funcall_argv (mrb=0x8c6010, self=..., mid=43, argc=0, argv=0x0) at /home/vagrant/git/mruby/src/vm.c:498
#54 0x0000000000425091 in mrb_method_missing (mrb=0x8c6010, name=708, self=..., args=...) at /home/vagrant/git/mruby/src/kernel.c:968
#55 0x000000000040dbd3 in mrb_vm_exec (mrb=0x8c6010, proc=0x8c92d0, pc=0x929fb4) at /home/vagrant/git/mruby/src/vm.c:1420
#56 0x000000000040ba83 in mrb_vm_run (mrb=0x8c6010, proc=0x8c92d0, self=..., stack_keep=0) at /home/vagrant/git/mruby/src/vm.c:930
#57 0x0000000000415505 in mrb_top_run (mrb=0x8c6010, proc=0x8c92d0, self=..., stack_keep=0) at /home/vagrant/git/mruby/src/vm.c:2964
#58 0x000000000044436e in mrb_load_exec (mrb=0x8c6010, p=0x91e1b0, c=0x91ca20) at /home/vagrant/git/mruby/mrbgems/mruby-compiler/core/parse.y:5840
#59 0x0000000000444404 in mrb_load_file_cxt (mrb=0x8c6010, f=0x91ddf0, c=0x91ca20) at /home/vagrant/git/mruby/mrbgems/mruby-compiler/core/parse.y:5849
#60 0x00000000004024ef in main (argc=2, argv=0x7ffc32347d88) at /home/vagrant/git/mruby/mrbgems/mruby-bin-mruby/tools/mruby/mruby.c:227
```
This issue was reported by https://hackerone.com/j0s3

**Comment by matz** [comment]
The fundamental issue is a misbehavior of `malloc(3)` in glibc. Under ulimit condition (like this one), it seems to return memory region which in part out of virtual memory space. The only thing we can do is reduce the arena consumption (like #3863).

**Comment by clayton-shopify** [comment]
OK, thanks for investigating.
