### ISSUE TITLE
stack-overflow in mrb_vm_exec

### ISSUE THREAD

**Issue by kristinaelise** [mruby/mruby#3920]
**Crashing Input**
```ruby
def method_missing(*x)
  Array to_s.to_enum .next_values, []
end

begin
   raise Stan$ardr
rescue
   raise
end
```
**ASAN Report**
```ruby
ASAN:DEADLYSIGNAL
=================================================================
==35456==ERROR: AddressSanitizer: stack-overflow on address 0x7ffeebd7f4b8 (pc 0x00010371b004 bp 0x7ffeebd876d0 sp 0x7ffeebd7f4c0 T0)
    #0 0x10371b003 in mrb_vm_exec vm.c:956
    #1 0x10371a014 in mrb_vm_run vm.c:935
    #2 0x103710b74 in mrb_run vm.c:2985
    #3 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #4 0x1036c6559 in mrb_instance_new class.c:1589
    #5 0x10372698f in mrb_vm_exec vm.c:1461
    #6 0x10371a014 in mrb_vm_run vm.c:935
    #7 0x1037108fa in mrb_run vm.c:2982
    #8 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #9 0x103712361 in mrb_f_send vm.c:571
    #10 0x10372698f in mrb_vm_exec vm.c:1461
    #11 0x10371a014 in mrb_vm_run vm.c:935
    #12 0x1037108fa in mrb_run vm.c:2982
    #13 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #14 0x103712361 in mrb_f_send vm.c:571
    #15 0x10372698f in mrb_vm_exec vm.c:1461
    #16 0x10371a014 in mrb_vm_run vm.c:935
    #17 0x1037108fa in mrb_run vm.c:2982
    #18 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #19 0x103712361 in mrb_f_send vm.c:571
    #20 0x10372698f in mrb_vm_exec vm.c:1461
    #21 0x10371a014 in mrb_vm_run vm.c:935
    #22 0x1037108fa in mrb_run vm.c:2982
    #23 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #24 0x103712361 in mrb_f_send vm.c:571
    #25 0x10372698f in mrb_vm_exec vm.c:1461
    #26 0x10371a014 in mrb_vm_run vm.c:935
    #27 0x1037108fa in mrb_run vm.c:2982
    #28 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #29 0x103712361 in mrb_f_send vm.c:571
    #30 0x10372698f in mrb_vm_exec vm.c:1461
    #31 0x10371a014 in mrb_vm_run vm.c:935
    #32 0x1037108fa in mrb_run vm.c:2982
    #33 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #34 0x103712361 in mrb_f_send vm.c:571
    #35 0x10372698f in mrb_vm_exec vm.c:1461
    #36 0x10371a014 in mrb_vm_run vm.c:935
    #37 0x1037108fa in mrb_run vm.c:2982
    #38 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #39 0x103712361 in mrb_f_send vm.c:571
    #40 0x10372698f in mrb_vm_exec vm.c:1461
    #41 0x10371a014 in mrb_vm_run vm.c:935
    #42 0x1037108fa in mrb_run vm.c:2982
    #43 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #44 0x103712361 in mrb_f_send vm.c:571
    #45 0x10372698f in mrb_vm_exec vm.c:1461
    #46 0x10371a014 in mrb_vm_run vm.c:935
    #47 0x1037108fa in mrb_run vm.c:2982
    #48 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #49 0x103712361 in mrb_f_send vm.c:571
    #50 0x10372698f in mrb_vm_exec vm.c:1461
    #51 0x10371a014 in mrb_vm_run vm.c:935
    #52 0x1037108fa in mrb_run vm.c:2982
    #53 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #54 0x103712361 in mrb_f_send vm.c:571
    #55 0x10372698f in mrb_vm_exec vm.c:1461
    #56 0x10371a014 in mrb_vm_run vm.c:935
    #57 0x1037108fa in mrb_run vm.c:2982
    #58 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #59 0x103712361 in mrb_f_send vm.c:571
    #60 0x10372698f in mrb_vm_exec vm.c:1461
    #61 0x10371a014 in mrb_vm_run vm.c:935
    #62 0x1037108fa in mrb_run vm.c:2982
    #63 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #64 0x103712361 in mrb_f_send vm.c:571
    #65 0x10372698f in mrb_vm_exec vm.c:1461
    #66 0x10371a014 in mrb_vm_run vm.c:935
    #67 0x1037108fa in mrb_run vm.c:2982
    #68 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #69 0x103712361 in mrb_f_send vm.c:571
    #70 0x10372698f in mrb_vm_exec vm.c:1461
    #71 0x10371a014 in mrb_vm_run vm.c:935
    #72 0x1037108fa in mrb_run vm.c:2982
    #73 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #74 0x103712361 in mrb_f_send vm.c:571
    #75 0x10372698f in mrb_vm_exec vm.c:1461
    #76 0x10371a014 in mrb_vm_run vm.c:935
    #77 0x1037108fa in mrb_run vm.c:2982
    #78 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #79 0x103712361 in mrb_f_send vm.c:571
    #80 0x10372698f in mrb_vm_exec vm.c:1461
    #81 0x10371a014 in mrb_vm_run vm.c:935
    #82 0x1037108fa in mrb_run vm.c:2982
    #83 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #84 0x103712361 in mrb_f_send vm.c:571
    #85 0x10372698f in mrb_vm_exec vm.c:1461
    #86 0x10371a014 in mrb_vm_run vm.c:935
    #87 0x1037108fa in mrb_run vm.c:2982
    #88 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #89 0x103712361 in mrb_f_send vm.c:571
    #90 0x10372698f in mrb_vm_exec vm.c:1461
    #91 0x10371a014 in mrb_vm_run vm.c:935
    #92 0x1037108fa in mrb_run vm.c:2982
    #93 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #94 0x103712361 in mrb_f_send vm.c:571
    #95 0x10372698f in mrb_vm_exec vm.c:1461
    #96 0x10371a014 in mrb_vm_run vm.c:935
    #97 0x1037108fa in mrb_run vm.c:2982
    #98 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #99 0x103712361 in mrb_f_send vm.c:571
    #100 0x10372698f in mrb_vm_exec vm.c:1461
    #101 0x10371a014 in mrb_vm_run vm.c:935
    #102 0x1037108fa in mrb_run vm.c:2982
    #103 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #104 0x103712361 in mrb_f_send vm.c:571
    #105 0x10372698f in mrb_vm_exec vm.c:1461
    #106 0x10371a014 in mrb_vm_run vm.c:935
    #107 0x1037108fa in mrb_run vm.c:2982
    #108 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #109 0x103712361 in mrb_f_send vm.c:571
    #110 0x10372698f in mrb_vm_exec vm.c:1461
    #111 0x10371a014 in mrb_vm_run vm.c:935
    #112 0x1037108fa in mrb_run vm.c:2982
    #113 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #114 0x103712361 in mrb_f_send vm.c:571
    #115 0x10372698f in mrb_vm_exec vm.c:1461
    #116 0x10371a014 in mrb_vm_run vm.c:935
    #117 0x1037108fa in mrb_run vm.c:2982
    #118 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #119 0x103712361 in mrb_f_send vm.c:571
    #120 0x10372698f in mrb_vm_exec vm.c:1461
    #121 0x10371a014 in mrb_vm_run vm.c:935
    #122 0x1037108fa in mrb_run vm.c:2982
    #123 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #124 0x103712361 in mrb_f_send vm.c:571
    #125 0x10372698f in mrb_vm_exec vm.c:1461
    #126 0x10371a014 in mrb_vm_run vm.c:935
    #127 0x1037108fa in mrb_run vm.c:2982
    #128 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #129 0x103712361 in mrb_f_send vm.c:571
    #130 0x10372698f in mrb_vm_exec vm.c:1461
    #131 0x10371a014 in mrb_vm_run vm.c:935
    #132 0x1037108fa in mrb_run vm.c:2982
    #133 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #134 0x103712361 in mrb_f_send vm.c:571
    #135 0x10372698f in mrb_vm_exec vm.c:1461
    #136 0x10371a014 in mrb_vm_run vm.c:935
    #137 0x1037108fa in mrb_run vm.c:2982
    #138 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #139 0x103712361 in mrb_f_send vm.c:571
    #140 0x10372698f in mrb_vm_exec vm.c:1461
    #141 0x10371a014 in mrb_vm_run vm.c:935
    #142 0x1037108fa in mrb_run vm.c:2982
    #143 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #144 0x103712361 in mrb_f_send vm.c:571
    #145 0x10372698f in mrb_vm_exec vm.c:1461
    #146 0x10371a014 in mrb_vm_run vm.c:935
    #147 0x1037108fa in mrb_run vm.c:2982
    #148 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #149 0x103712361 in mrb_f_send vm.c:571
    #150 0x10372698f in mrb_vm_exec vm.c:1461
    #151 0x10371a014 in mrb_vm_run vm.c:935
    #152 0x1037108fa in mrb_run vm.c:2982
    #153 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #154 0x103712361 in mrb_f_send vm.c:571
    #155 0x10372698f in mrb_vm_exec vm.c:1461
    #156 0x10371a014 in mrb_vm_run vm.c:935
    #157 0x1037108fa in mrb_run vm.c:2982
    #158 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #159 0x103712361 in mrb_f_send vm.c:571
    #160 0x10372698f in mrb_vm_exec vm.c:1461
    #161 0x10371a014 in mrb_vm_run vm.c:935
    #162 0x1037108fa in mrb_run vm.c:2982
    #163 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #164 0x103712361 in mrb_f_send vm.c:571
    #165 0x10372698f in mrb_vm_exec vm.c:1461
    #166 0x10371a014 in mrb_vm_run vm.c:935
    #167 0x1037108fa in mrb_run vm.c:2982
    #168 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #169 0x103712361 in mrb_f_send vm.c:571
    #170 0x10372698f in mrb_vm_exec vm.c:1461
    #171 0x10371a014 in mrb_vm_run vm.c:935
    #172 0x1037108fa in mrb_run vm.c:2982
    #173 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #174 0x103712361 in mrb_f_send vm.c:571
    #175 0x10372698f in mrb_vm_exec vm.c:1461
    #176 0x10371a014 in mrb_vm_run vm.c:935
    #177 0x1037108fa in mrb_run vm.c:2982
    #178 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #179 0x103712361 in mrb_f_send vm.c:571
    #180 0x10372698f in mrb_vm_exec vm.c:1461
    #181 0x10371a014 in mrb_vm_run vm.c:935
    #182 0x1037108fa in mrb_run vm.c:2982
    #183 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #184 0x103712361 in mrb_f_send vm.c:571
    #185 0x10372698f in mrb_vm_exec vm.c:1461
    #186 0x10371a014 in mrb_vm_run vm.c:935
    #187 0x1037108fa in mrb_run vm.c:2982
    #188 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #189 0x103712361 in mrb_f_send vm.c:571
    #190 0x10372698f in mrb_vm_exec vm.c:1461
    #191 0x10371a014 in mrb_vm_run vm.c:935
    #192 0x1037108fa in mrb_run vm.c:2982
    #193 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #194 0x103712361 in mrb_f_send vm.c:571
    #195 0x10372698f in mrb_vm_exec vm.c:1461
    #196 0x10371a014 in mrb_vm_run vm.c:935
    #197 0x1037108fa in mrb_run vm.c:2982
    #198 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #199 0x103712361 in mrb_f_send vm.c:571
    #200 0x10372698f in mrb_vm_exec vm.c:1461
    #201 0x10371a014 in mrb_vm_run vm.c:935
    #202 0x1037108fa in mrb_run vm.c:2982
    #203 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #204 0x103712361 in mrb_f_send vm.c:571
    #205 0x10372698f in mrb_vm_exec vm.c:1461
    #206 0x10371a014 in mrb_vm_run vm.c:935
    #207 0x1037108fa in mrb_run vm.c:2982
    #208 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #209 0x103712361 in mrb_f_send vm.c:571
    #210 0x10372698f in mrb_vm_exec vm.c:1461
    #211 0x10371a014 in mrb_vm_run vm.c:935
    #212 0x1037108fa in mrb_run vm.c:2982
    #213 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #214 0x103712361 in mrb_f_send vm.c:571
    #215 0x10372698f in mrb_vm_exec vm.c:1461
    #216 0x10371a014 in mrb_vm_run vm.c:935
    #217 0x1037108fa in mrb_run vm.c:2982
    #218 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #219 0x103712361 in mrb_f_send vm.c:571
    #220 0x10372698f in mrb_vm_exec vm.c:1461
    #221 0x10371a014 in mrb_vm_run vm.c:935
    #222 0x1037108fa in mrb_run vm.c:2982
    #223 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #224 0x103712361 in mrb_f_send vm.c:571
    #225 0x10372698f in mrb_vm_exec vm.c:1461
    #226 0x10371a014 in mrb_vm_run vm.c:935
    #227 0x1037108fa in mrb_run vm.c:2982
    #228 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #229 0x103712361 in mrb_f_send vm.c:571
    #230 0x10372698f in mrb_vm_exec vm.c:1461
    #231 0x10371a014 in mrb_vm_run vm.c:935
    #232 0x1037108fa in mrb_run vm.c:2982
    #233 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #234 0x103712361 in mrb_f_send vm.c:571
    #235 0x10372698f in mrb_vm_exec vm.c:1461
    #236 0x10371a014 in mrb_vm_run vm.c:935
    #237 0x1037108fa in mrb_run vm.c:2982
    #238 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #239 0x103712361 in mrb_f_send vm.c:571
    #240 0x10372698f in mrb_vm_exec vm.c:1461
    #241 0x10371a014 in mrb_vm_run vm.c:935
    #242 0x1037108fa in mrb_run vm.c:2982
    #243 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #244 0x103712361 in mrb_f_send vm.c:571
    #245 0x10372698f in mrb_vm_exec vm.c:1461
    #246 0x10371a014 in mrb_vm_run vm.c:935
    #247 0x1037108fa in mrb_run vm.c:2982
    #248 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #249 0x103712361 in mrb_f_send vm.c:571
    #250 0x10372698f in mrb_vm_exec vm.c:1461
    #251 0x10371a014 in mrb_vm_run vm.c:935
    #252 0x1037108fa in mrb_run vm.c:2982
    #253 0x10370e5aa in mrb_funcall_with_block vm.c:493
    #254 0x103712361 in mrb_f_send vm.c:571
    #255 0x10372698f in mrb_vm_exec vm.c:1461

SUMMARY: AddressSanitizer: stack-overflow vm.c:956 in mrb_vm_exec
==35456==ABORTING
Abort trap: 6
```

**Reported By**
https://hackerone.com/develbranch
  
**Other details**
Crashing in both `mruby` and `mirb`.

**Comment by matz** [comment]
This is a duplication of #3789 and #3854
