### ISSUE TITLE
The behavior of Fiber#alive? on fiber and proc

### ISSUE THREAD

**Issue by matsumotory** [mruby/mruby#3954]
Is the following example the intended behavior?

```ruby
p1 = Proc.new do 
  %w(hoge fuga foo).each do |s|
    puts s
    Fiber.yield
  end
end

f = Fiber.new do
  p1.call
end

p2 = Proc.new do
  r = f.resume
  f.alive?
end

p p2.call
p p2.call
p p2.call
p p2.call
```

- mruby

```
$ ./mruby/bin/mruby loop.rb
hoge
true
fuga
true
foo
true
false
```

- CRuby

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

$ ruby loop.rb 
hoge
loop.rb:14:in `block in <main>': undefined method `alive?' for #<Fiber:0x00000000cb29d8> (NoMethodError)
        from loop.rb:17:in `<main>'
```

**Comment by matz** [comment]
In CRuby, you need to `require "fiber"` to use fiber API.

**Comment by matsumotory** [comment]
Oh sorry... thanks!
