### ISSUE TITLE
conf.gembox 'full-core' build failed

### ISSUE THREAD

**Issue by arkceajin** [mruby/mruby#4040]
I want use  
```
conf.gem :github => 'mattn/mruby-require'  
conf.gembox 'full-core' 
```
in `build_config.rb` 
But I got following error in 1.4.1 version:
```
ar: creating D:/MRuby/mruby-1.4.1/build/test/lib/libmruby.a
rake aborted!
No such file or directory @ rb_sysopen - D:/MRuby/mruby-1.4.1/build/host/bin/mrbc
rakefile:48:in `block (2 levels) in <top (required)>'
```
remove `conf.gem :github => 'mattn/mruby-require' ` got the same.

BTW `required` is the basic function of ruby, Why don't put into the core gems? Or any other way to import source file?

GCC: 6.3.0

**Comment by matz** [comment]
The error message indicates you have failed to build `mrbc`. But I don't know why.

BTW, mruby supports platforms that do not have any file systems. That's the reason not to support `require` as a built-in method.

**Comment by arkceajin** [comment]
Thanks, I am using Mingw32 6.3.0 & Ruby 2.3.3. tried Win 10 & Win 7 both got the same when full core, and no problem with default gems:
```
CC    mrbgems/mruby-class-ext/src/class.c -> build/test/mrbgems/mruby-class-ext/src/class.o
CC    build/test/mrbgems/mruby-class-ext/gem_init.c -> build/test/mrbgems/mruby-class-ext/gem_init.o
CC    mrbgems/mruby-compiler/core/codegen.c -> build/test/mrbgems/mruby-compiler/core/codegen.o
YACC  mrbgems/mruby-compiler/core/parse.y -> build/test/mrbgems/mruby-compiler/core/y.tab.c
YACC  mrbgems/mruby-compiler/core/parse.y -> build/test/mrbgems/mruby-compiler/core/y.tab.c
CC    build/test/mrbgems/mruby-compiler/core/y.tab.c -> build/test/mrbgems/mruby-compiler/core/y.tab.o
CC    build/test/mrbgems/mruby-compiler/core/y.tab.c -> build/test/mrbgems/mruby-compiler/core/y.tab.o
CC    mrbgems/mruby-error/src/exception.c -> build/test/mrbgems/mruby-error/src/exception.o
CC    build/test/mrbgems/mruby-error/gem_init.c -> build/test/mrbgems/mruby-error/gem_init.o
CC    build/test/mrbgems/gem_init.c -> build/test/mrbgems/gem_init.o
AR    build/test/lib/libmruby.a
ar: creating D:/MRuby/mruby-1.4.1/build/test/lib/libmruby.a
rake aborted!
No such file or directory @ rb_sysopen - D:/MRuby/mruby-1.4.1/build/host/bin/mrbc
rakefile:48:in `block (2 levels) in <top (required)>'
```

**Comment by take-cheeze** [comment]
Seems like you don't have `host` build: https://github.com/mruby/mruby/issues/3959
Rename `test` build to `host`.

**Comment by arkceajin** [comment]
@take-cheeze Thanks for the solution. 
I only modify the `build_config.rb` default to `conf.gembox 'full-core'` in host.
as you mentioned:

> You need 'host' MRuby::Build (which is MRuby::Build without name) 

So the host suppose exists.
then run ` ruby minirake -t` got these:

```
AR    build/test/lib/libmruby.a
ar: creating D:/MRuby/mruby-1.4.1/build/test/lib/libmruby.a
Execute D:/MRuby/mruby-1.4.1/build/test/lib/libmruby.flags.mak
Invoke D:/MRuby/mruby-1.4.1/bin/mruby-config.bat (already=[], needed=[true])
Invoke D:/MRuby/mruby-1.4.1/build/host/bin/mruby-config.bat (already=[], needed=[true])
Invoke D:/MRuby/mruby-1.4.1/build/host/lib/libmruby.a (already=[true], needed=[false])
Execute D:/MRuby/mruby-1.4.1/build/host/bin/mruby-config.bat
Execute D:/MRuby/mruby-1.4.1/bin/mruby-config.bat
Invoke D:/MRuby/mruby-1.4.1/bin/mrbc (already=[], needed=[true])
Invoke D:/MRuby/mruby-1.4.1/build/host/bin/mrbc (already=[true], needed=[true])
Execute D:/MRuby/mruby-1.4.1/bin/mrbc
rake aborted!
No such file or directory @ rb_sysopen - D:/MRuby/mruby-1.4.1/build/host/bin/mrbc
C:/RailsInstaller/Ruby23/lib/ruby/2.3.0/fileutils.rb:1392:in `initialize'
C:/RailsInstaller/Ruby23/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
C:/RailsInstaller/Ruby23/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
C:/RailsInstaller/Ruby23/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
C:/RailsInstaller/Ruby23/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
C:/RailsInstaller/Ruby23/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
C:/RailsInstaller/Ruby23/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
C:/RailsInstaller/Ruby23/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
C:/RailsInstaller/Ruby23/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
rakefile:48:in `block (2 levels) in <top (required)>'
minirake:104:in `block in execute'
minirake:104:in `each'
minirake:104:in `execute'
minirake:96:in `invoke'
minirake:95:in `block in invoke'
minirake:95:in `each'
minirake:95:in `invoke'
minirake:95:in `block in invoke'
minirake:95:in `each'
minirake:95:in `invoke'
minirake:466:in `block in run'
minirake:465:in `each'
minirake:465:in `run'
minirake:483:in `<main>'
```

**Comment by arkceajin** [comment]
BTW the `mrbc` did generate under bin folder.

**Comment by matz** [comment]
You have `bin/mrbc` but how about `build/host/bin/mrbc`? That's what required now.

**Comment by take-cheeze** [comment]
At least with mingw-w64 64bit I don't get that error.

**Comment by matz** [comment]
Me neither on Linux Ubuntu box.

**Comment by take-cheeze** [comment]
Seems like `D:/MRuby/mruby-1.4.1/build/host/bin/mrbc` doesn't have `.exe`
https://github.com/mruby/mruby/blob/93f5f225772c398be6e409da3d3ef0f07ffbe1cf/build_config.rb#L73-L78

**Comment by arkceajin** [comment]
```
  # file extensions
   conf.exts do |exts|
     exts.object = '.o'
     exts.executable = '.exe' # '.exe' if Windows
     exts.library = '.a'
   end
```

Got the same, I will try mingw64.

**Comment by arkceajin** [comment]
`build/host/bin/mrbc` also generated.

**Comment by matz** [comment]
Closing — `conf.gembox 'full-core'` build issue against mruby 1.4.1 (8 years old, multiple major releases since). Not reproducible against current master.
