### ISSUE TITLE
Invalid read in str_make_shared

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#4042]
The following input demonstrates a crash, when supplied to mirb:
```ruby
def aa(n)
    if n >= 0
      instance_eval(z)
    end
rescue
    aa (n-1)
end
aa(0x22)
r0=("z".."x")
array=Array.new(10)
array.to_s.x
array_clone=array.clone 
aa(0x100)
r=("z".."x")
r0.initialize_copy r
r=0
array=Array.new(0x26f)
r0.to_s
```
Note that this input only produces a crash in mirb, not mruby.

A bisect shows that the crash began in 50a9c5d7c704e84c6bdec9affa270824fed02034, so that change could be related.

ASAN report:
```
ASAN:DEADLYSIGNAL
=================================================================
==82811==ERROR: AddressSanitizer: SEGV on unknown address 0x000100000012 (pc 0x00010aac511e bp 0x7ffee523d710 sp 0x7ffee523d400 T0)
==82811==The signal is caused by a READ memory access.
    #0 0x10aac511d in str_make_shared string.c:355
    #1 0x10aa9d8de in str_replace string.c:530
    #2 0x10aa9c737 in mrb_str_dup string.c:1039
    #3 0x10aaf129b in range_to_s range.c:302
    #4 0x10aa648ec in mrb_vm_exec vm.c:1476
    #5 0x10aa57ecb in mrb_vm_run vm.c:948
    #6 0x10a9ba558 in main mirb.c:631
    #7 0x7fff7573c014 in start (libdyld.dylib:x86_64+0x1014)

==82811==Register values:
rax = 0x0000100000000000  rbx = 0x00007ffee523d760  rcx = 0x0000000100000012  rdx = 0x0000000100000012
rdi = 0x0000614000000000  rsi = 0x0000100020000002  rbp = 0x00007ffee523d710  rsp = 0x00007ffee523d400
 r8 = 0x00001c5e00014146   r9 = 0x00001c5e00014100  r10 = 0x95f506342c480000  r11 = 0x000062eef53ca210
r12 = 0x00007ffee523dc60  r13 = 0x00007ffee523dc80  r14 = 0x00007ffee523dc20  r15 = 0x00007ffee523dc40
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV string.c:355 in str_make_shared
==82811==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/ahihi

**Comment by clayton-shopify** [comment]
This modified input causes a crash in mruby as well:
```ruby
def aa(n)
    if n >= 0
      instance_eval(z)
    end
rescue
    aa (n-1)
end
aa(0x22)
puts r0=("z".."x")
puts array=Array.new(10)
puts array.to_s
puts array_clone=array.clone
aa(0x100)
puts r=("z".."x")
puts r0.initialize_copy r
puts r=0
puts array=Array.new(0x26f)
puts r0.to_s
```
ASAN report:
```
ASAN:DEADLYSIGNAL
=================================================================
==85848==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fff75a4dfc9 bp 0x7ffeefb87a00 sp 0x7ffeefb87a00 T0)
==85848==The signal is caused by a READ memory access.
==85848==Hint: address points to the zero page.
    #0 0x7fff75a4dfc8 in _platform_memmove$VARIANT$Haswell (libsystem_platform.dylib:x86_64+0x4fc8)
    #1 0x10055c58f in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4f58f)
    #2 0x1000dc9c8 in mrb_ary_ref array.c:659
    #3 0x1000e85ec in mrb_ary_aget array.c:870
    #4 0x100118d9c in mrb_vm_exec vm.c:1476
    #5 0x10010c37b in mrb_vm_run vm.c:948
    #6 0x1001442f3 in mrb_top_run vm.c:3012
    #7 0x1003430a7 in mrb_load_exec parse.y:5835
    #8 0x100343ee9 in mrb_load_file_cxt parse.y:5844
    #9 0x10006f895 in main mruby.c:279
    #10 0x7fff7573c014 in start (libdyld.dylib:x86_64+0x1014)

==85848==Register values:
rax = 0x00007ffeefb882a0  rbx = 0x00000001012ed880  rcx = 0x00000fffddf71001  rdx = 0x0000000000000008
rdi = 0x00007ffeefb882a0  rsi = 0x0000000000000000  rbp = 0x00007ffeefb87a00  rsp = 0x00007ffeefb87a00
 r8 = 0x00007ffeefb882c0   r9 = 0x00001fffddf71058  r10 = 0xe5cf2c5054120096  r11 = 0x00007ffeefb882a0
r12 = 0x0000000000000010  r13 = 0x00007ffeefb8fbc0  r14 = 0x0000000000000000  r15 = 0x00007ffeefb882a0
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_platform.dylib:x86_64+0x4fc8) in _platform_memmove$VARIANT$Haswell
==85848==ABORTING
Abort trap: 6
```
