### ISSUE TITLE
Null pointer dereference in mrb_method_search_vm

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#4096]
The following input demonstrates a crash, when supplied to mirb:
```ruby
return * NoMethodError
```
Note that the crash only occurs in mirb, not mruby.

ASAN report:
```
ASAN:DEADLYSIGNAL
=================================================================
==25867==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000021 (pc 0x0001081a122c bp 0x7ffee7a95fd0 sp 0x7ffee7a95e20 T0)
==25867==The signal is caused by a READ memory access.
==25867==Hint: address points to the zero page.
    #0 0x1081a122b in mrb_method_search_vm (mirb:x86_64+0x10004922b)
    #1 0x108206a82 in mrb_vm_exec (mirb:x86_64+0x1000aea82)
    #2 0x1081f7b3d in mrb_vm_run (mirb:x86_64+0x10009fb3d)
    #3 0x1081eec1f in mrb_run (mirb:x86_64+0x100096c1f)
    #4 0x1081ec417 in mrb_funcall_with_block (mirb:x86_64+0x100094417)
    #5 0x1081e91df in mrb_funcall_with_block (mirb:x86_64+0x1000911df)
    #6 0x1081e88b9 in mrb_funcall_argv (mirb:x86_64+0x1000908b9)
    #7 0x1081e82f6 in mrb_funcall (mirb:x86_64+0x1000902f6)
    #8 0x10815e876 in p (mirb:x86_64+0x100006876)
    #9 0x10815c3e5 in main (mirb:x86_64+0x1000043e5)
    #10 0x7fff71cb6014 in start (libdyld.dylib:x86_64+0x1014)

==25867==Register values:
rax = 0x0000000000000021  rbx = 0x00007ffee7a95e80  rcx = 0x0000000000000021  rdx = 0x0000100000000004
rdi = 0x00007ffee7aa1c20  rsi = 0x00001fffdcf52bc4  rbp = 0x00007ffee7a95fd0  rsp = 0x00007ffee7a95e20
 r8 = 0x00007ffee7a95e40   r9 = 0x00007ffee7a95e60  r10 = 0x000000000000002b  r11 = 0x00007ffee7aa1c20
r12 = 0x00007ffee7aa1820  r13 = 0x00007ffee7aa1840  r14 = 0x00001fffdcf54384  r15 = 0x0000100000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (mirb:x86_64+0x10004922b) in mrb_method_search_vm
==25867==ABORTING
Abort trap: 6
```
This issue was reported by https://hackerone.com/ahihi

**Comment by matz** [comment]
It's a duplicate of #4094.
