### ISSUE TITLE
Null pointer dereference in mrb_ary_push

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#4135]
The following input demonstrates a crash:
```ruby
def method_missing(*)
end[*0]%=begin{0=>0}
00end
```
It appears this problem was introduced to the master branch in 93bab387a71841fabe31ae3e0301417da543cbf8.

ASAN report:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==59194==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0001092e1c40 bp 0x7ffee6970010 sp 0x7ffee696fde0 T0)
==59194==The signal is caused by a READ memory access.
==59194==Hint: address points to the zero page.
    #0 0x1092e1c3f in mrb_ary_push (mruby:x86_64+0x100060c3f)
    #1 0x10934697f in mrb_vm_exec (mruby:x86_64+0x1000c597f)
    #2 0x109314589 in mrb_vm_run (mruby:x86_64+0x100093589)
    #3 0x109373fef in mrb_top_run (mruby:x86_64+0x1000f2fef)
    #4 0x1095c28d1 in mrb_load_exec (mruby:x86_64+0x1003418d1)
    #5 0x1095c3469 in mrb_load_file_cxt (mruby:x86_64+0x100342469)
    #6 0x109283f16 in main (mruby:x86_64+0x100002f16)
    #7 0x7fff71cb6014 in start (libdyld.dylib:x86_64+0x1014)

==59194==Register values:
rax = 0x0000000000000000  rbx = 0x00007ffee696fe40  rcx = 0x00007ffee696fe00  rdx = 0x0000000000000000
rdi = 0x00007ffee696fe00  rsi = 0x0000100000000000  rbp = 0x00007ffee6970010  rsp = 0x00007ffee696fde0
 r8 = 0x00001fffdcd2dfc0   r9 = 0x00007ffee696fe20  r10 = 0x000000010a743788  r11 = 0xa9b713bbd641001e
r12 = 0x00007ffee697b960  r13 = 0x00007ffee697b980  r14 = 0x00001fffdcd2f72c  r15 = 0x0000100000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (mruby:x86_64+0x100060c3f) in mrb_ary_push
==59194==ABORTING
Abort trap: 6
```
This issue was reported by Dinko Galetic & Denis Kasak (https://hackerone.com/dgaletic).

**Comment by clayton-shopify** [comment]
The following crashing input was also reported:
```ruby
def method_missing(*)
end
{}.[]0[*0] %=
begin{0=>0}
00end
```
