### ISSUE TITLE
undefined left shift in enum.c

### ISSUE THREAD

**Issue by geeknik** [mruby/mruby#4161]
While testing mruby, we discovered a crafted script that triggers an undefined left shift in enum.c.

Version:
`git c3188ca`

Script:
```
class N begin()ensure begin(1.times{|*x|begin begin(80.times{N=x<<=x|x}*0)
()end end}*0)end
end
end
```

Stack:
```
/root/mruby/src/enum.c:33:15: runtime error: left shift of 340037049414196627 by 10 places cannot be represented in type 'mrb_int' (aka 'long')
    #0 0x60c41b in enum_update_hash /root/mruby/src/enum.c:33:15
    #1 0x4e49b0 in mrb_vm_exec /root/mruby/src/vm.c:1454:18
    #2 0x4d061c in mrb_vm_run /root/mruby/src/vm.c:972:12
    #3 0x4c62b9 in mrb_funcall_with_block /root/mruby/src/vm.c:528:13
    #4 0x4c3baa in mrb_funcall_argv /root/mruby/src/vm.c:538:10
    #5 0x4c3baa in mrb_funcall /root/mruby/src/vm.c:395
    #6 0x605b5f in sg_hash_func /root/mruby/src/hash.c:76:10
    #7 0x604edc in sg_index /root/mruby/src/hash.c:215:11
    #8 0x5fa55c in mrb_hash_set /root/mruby/src/hash.c:721:3
    #9 0x6008d4 in mrb_hash_aset /root/mruby/src/hash.c:1124:3
    #10 0x4e49b0 in mrb_vm_exec /root/mruby/src/vm.c:1454:18
    #11 0x4d061c in mrb_vm_run /root/mruby/src/vm.c:972:12
    #12 0x546c8c in mrb_top_run /root/mruby/src/vm.c
    #13 0x5a0c8d in mrb_load_exec /root/mruby/mrbgems/mruby-compiler/core/parse.y:6013:7
    #14 0x425a36 in main /root/mruby/mrbgems/mruby-bin-mruby/tools/mruby/mruby.c:280:11
    #15 0x7fc0a875a1c0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x211c0)
    #16 0x404889 in _start (/root/mruby/bin/mruby+0x404889)

Aborted
```

**Comment by matz** [comment]
I cannot reproduce the issue on my machine. Could you check adding `(mrb_int)` after `=` operator in line 33 of `src/enum.c` like the following?
```
  h ^= (mrb_int)(hv << (index % 16));
```

**Comment by geeknik** [comment]
The only thing the addition of (mrb_int) to that line did was speed up the failure, it no long hangs for an indeterminate amount of time.

**Comment by matz** [comment]
Hmm, then I have no clue to fix the issue. Any idea? Anyone?
