### ISSUE TITLE
Segmentation fault with malformed mruby bytecode

### ISSUE THREAD

**Issue by bshastry** [mruby/mruby#4257]
Hello,

This bytecode file causes a segmentation fault in mruby (wild read).

```
$ xxd crash.mrb 
00000000: 5249 5445 3030 3036 b4b9 0000 001e 4d41  RITE0006......MA
00000010: 545a 3030 3030 4952 4550 454e 4400       TZ0000IREPEND.

$ ./bin/mruby -b crash.mrb 1> asan.log

$ cat asan.log
AddressSanitizer:DEADLYSIGNAL
=================================================================
==31872==ERROR: AddressSanitizer: SEGV on unknown address 0x6030454e97f6 (pc 0x00000051bff0 bp 0x607000011740 sp 0x7ffc8e089d40 T0)
==31872==The signal is caused by a READ memory access.
    #0 0x51bfef in read_section_lv /home/bhargava/work/github/mruby/src/load.c:509
    #1 0x51bfef in read_irep /home/bhargava/work/github/mruby/src/load.c:600
    #2 0x51c80c in mrb_read_irep_file /home/bhargava/work/github/mruby/src/load.c:691
    #3 0x51c80c in mrb_load_irep_file_cxt /home/bhargava/work/github/mruby/src/load.c:701
    #4 0x41bcee in main /home/bhargava/work/github/mruby/mrbgems/mruby-bin-mruby/tools/mruby/mruby.c:277
    #5 0x7f708c777b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #6 0x41be89 in _start (/home/bhargava/work/github/mruby/bin/mruby+0x41be89)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/bhargava/work/github/mruby/src/load.c:509 in read_section_lv
==31872==ABORTING
```

HTH.

**Comment by matz** [comment]
Currently, protection from malformed binary is not supported.  Mostly because safety needs more code & memory.

**Comment by matz** [comment]
Closing — the modern bytecode loader (`mrb_read_irep_buf` with explicit bounds checks) raises `ScriptError` for malformed input rather than segfaulting. The original RITE0006 format is also long obsolete (current is RITE0400). Bytecode-fuzz hardening is also continuously run via oss-fuzz.
