### ISSUE TITLE
Null pointer dereference in mrb_str_cat_str

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#4504]
When mruby is built with the mruby-method gem, the following input demonstrates a crash:
```ruby
class A
  def self.to_s; end
  def self.inspect; end
  def m; end
end

class B < A
end

class Symbol
  def to_s; end
end

A.new.method(:m).to_s
B.new.method(:m).to_s
```
This occurs because non-String objects are passed into `mrb_str_cat_str`.

ASAN report:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==38222==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000102aea9c1 bp 0x7ffeed1fddd0 sp 0x7ffeed1fdb40 T0)
==38222==The signal is caused by a READ memory access.
==38222==Hint: address points to the zero page.
    #0 0x102aea9c0 in mrb_str_cat_str (mruby:x86_64+0x1000f79c0)
    #1 0x102d56d8c in method_to_s (mruby:x86_64+0x100363d8c)
    #2 0x102a94d64 in mrb_vm_exec (mruby:x86_64+0x1000a1d64)
    #3 0x102a832aa in mrb_vm_run (mruby:x86_64+0x1000902aa)
    #4 0x102ae299c in mrb_top_run (mruby:x86_64+0x1000ef99c)
    #5 0x102d2dbae in mrb_load_exec (mruby:x86_64+0x10033abae)
    #6 0x102d2ea69 in mrb_load_file_cxt (mruby:x86_64+0x10033ba69)
    #7 0x1029f6407 in main (mruby:x86_64+0x100003407)
    #8 0x7fff750cc3d4 in start (libdyld.dylib:x86_64+0x163d4)

==38222==Register values:
rax = 0x0000000000000000  rbx = 0x00007ffeed1fdbc0  rcx = 0x0000000000000000  rdx = 0x0000100000000000
rdi = 0x000061a000000000  rsi = 0x0000100000000000  rbp = 0x00007ffeed1fddd0  rsp = 0x00007ffeed1fdb40
 r8 = 0x0000100000000000   r9 = 0x00007ffeed1fdb80  r10 = 0x00001fffdda3fb70  r11 = 0xa4197df1d7c4008c
r12 = 0x00007ffeed1fdf40  r13 = 0x00007ffeed1fdf60  r14 = 0x00007ffeed1fdf00  r15 = 0x00007ffeed1fdf20
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (mruby:x86_64+0x1000f79c0) in mrb_str_cat_str
==38222==ABORTING
Abort trap: 6
```
This issue was reported by @shuujii, who proposed the following fix:
```diff
diff --git a/include/mruby/class.h b/include/mruby/class.h
index a6872453..ae945b4f 100644
--- a/include/mruby/class.h
+++ b/include/mruby/class.h
@@ -89,6 +89,7 @@ mrb_value mrb_instance_new(mrb_state *mrb, mrb_value cv);
 
 void mrb_class_name_class(mrb_state*, struct RClass*, struct RClass*, mrb_sym);
 mrb_value mrb_class_find_path(mrb_state*, struct RClass*);
+mrb_value mrb_mod_to_s(mrb_state*, mrb_value);
 void mrb_gc_mark_mt(mrb_state*, struct RClass*);
 size_t mrb_gc_mark_mt_size(mrb_state*, struct RClass*);
 void mrb_gc_free_mt(mrb_state*, struct RClass*);
diff --git a/mrbgems/mruby-method/src/method.c b/mrbgems/mruby-method/src/method.c
index 9f113422..29e0f1fc 100644
--- a/mrbgems/mruby-method/src/method.c
+++ b/mrbgems/mruby-method/src/method.c
@@ -264,22 +264,21 @@ method_to_s(mrb_state *mrb, mrb_value self)
   mrb_value klass = mrb_iv_get(mrb, self, mrb_intern_lit(mrb, "@klass"));
   mrb_value name = mrb_iv_get(mrb, self, mrb_intern_lit(mrb, "@name"));
   mrb_value str = mrb_str_new_lit(mrb, "#<");
-  struct RClass *rklass;
+  mrb_int len;
 
   mrb_str_cat_cstr(mrb, str, mrb_obj_classname(mrb, self));
   mrb_str_cat_lit(mrb, str, ": ");
-  rklass = mrb_class_ptr(klass);
-  if (mrb_class_ptr(owner) == rklass) {
-    mrb_str_cat_str(mrb, str, mrb_funcall(mrb, owner, "to_s", 0));
+  if (mrb_class_ptr(owner) == mrb_class_ptr(klass)) {
+    mrb_str_cat_str(mrb, str, mrb_mod_to_s(mrb, owner));
     mrb_str_cat_lit(mrb, str, "#");
-    mrb_str_cat_str(mrb, str, mrb_funcall(mrb, name, "to_s", 0));
+    mrb_str_cat(mrb, str, mrb_sym2name_len(mrb, mrb_symbol(name), &len), len);
   }
   else {
-    mrb_str_cat_cstr(mrb, str, mrb_class_name(mrb, rklass));
+    mrb_str_cat_str(mrb, str, mrb_mod_to_s(mrb, klass));
     mrb_str_cat_lit(mrb, str, "(");
-    mrb_str_cat_str(mrb, str, mrb_funcall(mrb, owner, "to_s", 0));
+    mrb_str_cat_str(mrb, str, mrb_mod_to_s(mrb, owner));
     mrb_str_cat_lit(mrb, str, ")#");
-    mrb_str_cat_str(mrb, str, mrb_funcall(mrb, name, "to_s", 0));
+    mrb_str_cat(mrb, str, mrb_sym2name_len(mrb, mrb_symbol(name), &len), len);
   }
   mrb_str_cat_lit(mrb, str, ">");
   return str;
diff --git a/mrbgems/mruby-method/test/method.rb b/mrbgems/mruby-method/test/method.rb
index 0b67d3e6..a1416cca 100644
--- a/mrbgems/mruby-method/test/method.rb
+++ b/mrbgems/mruby-method/test/method.rb
@@ -210,7 +210,7 @@ def o.bar
   assert_equal 42, o.bar(&3.method(:+))
 end
 
-assert 'to_s' do
+assert 'Method#to_s' do
   o = Object.new
   def o.foo; end
   m = o.method(:foo)
@@ -224,6 +224,33 @@ def o.foo; end
   assert_equal("#<UnboundMethod: #{ c.inspect }#foo>", m.inspect)
 end
 
+assert 'Method#to_s (#to_s of owner and Symbol return non-string)' do
+  begin
+    class ToS1
+      def self.to_s; end
+      def self.inspect; end
+      def m; end
+    end
+
+    class ToS2 < ToS1
+    end
+
+    class Symbol
+      alias original_to_s to_s
+      def to_s
+        original_to_s unless self == :m
+      end
+    end
+
+    assert_equal("#<Method: ToS1#m>", ToS1.new.method(:m).to_s)
+    assert_equal("#<Method: ToS2(ToS1)#m>", ToS2.new.method(:m).to_s)
+  ensure
+    class Symbol
+      alias to_s original_to_s
+    end
+  end
+end
+
 assert 'owner' do
   c = Class.new do
     def foo; end
```

**Comment by matz** [comment]
Fixed by 6724416
