### ISSUE TITLE
Null pointer dereference in mrb_check_frozen

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#4519]
The following input demonstrates a crash:
```ruby
0.remove_instance_variable '@a'
```
It appears the issue was introduced in 030dd6655e47dad4af4b48a74646712c00684698.

ASAN report:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==33115==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010b5630c2 bp 0x7ffee48512f0 sp 0x7ffee48512c0 T0)
==33115==The signal is caused by a READ memory access.
==33115==Hint: address points to the zero page.
    #0 0x10b5630c1 in mrb_check_frozen (mruby:x86_64+0x1001c30c1)
    #1 0x10b567d3e in mrb_iv_remove (mruby:x86_64+0x1001c7d3e)
    #2 0x10b3c1ded in mrb_obj_remove_instance_variable (mruby:x86_64+0x100021ded)
    #3 0x10b442014 in mrb_vm_exec (mruby:x86_64+0x1000a2014)
    #4 0x10b43055a in mrb_vm_run (mruby:x86_64+0x10009055a)
    #5 0x10b48fc4c in mrb_top_run (mruby:x86_64+0x1000efc4c)
    #6 0x10b6daa5e in mrb_load_exec (mruby:x86_64+0x10033aa5e)
    #7 0x10b6db919 in mrb_load_file_cxt (mruby:x86_64+0x10033b919)
    #8 0x10b3a36b7 in main (mruby:x86_64+0x1000036b7)
    #9 0x7fff750cc3d4 in start (libdyld.dylib:x86_64+0x163d4)

==33115==Register values:
rax = 0x0000000000000000  rbx = 0x00007ffee4851360  rcx = 0x0000000000000000  rdx = 0x000061a000000080
rdi = 0x0000100000000000  rsi = 0x0000000000000000  rbp = 0x00007ffee48512f0  rsp = 0x00007ffee48512c0
 r8 = 0x00007ffee4851340   r9 = 0x00001fffdc90a268  r10 = 0x0000100000000000  r11 = 0xffffffffffffffa0
r12 = 0x00007ffee485cee0  r13 = 0x00007ffee485cf00  r14 = 0x00001fffdc90a2a0  r15 = 0x00007ffee485cec0
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (mruby:x86_64+0x1001c30c1) in mrb_check_frozen
==33115==ABORTING
Abort trap: 6
```
This issue was reported by Dinko Galetic & Denis Kasak (https://hackerone.com/dgaletic).

**Comment by dkasak** [comment]
The problem is `mrb_iv_remove` assumes that the passed `mrb_value` is an object when it can also be an immediate, in which case taking its pointer is incorrect. I submitted a PR to fix this.
