### ISSUE TITLE
Build for Android

### ISSUE THREAD

**Issue by IK-O** [mruby/mruby#4563]
I tried to build for Android referring to [this issue(#3444)](https://github.com/mruby/mruby/issues/3444).

Rake command failed widh errors

> rake aborted!
> Don't know how to build task 'android-arm64-v8a' (see --tasks)
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task_manager.rb:59:in `[]'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:159:in `invoke_task'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
> /home/pc/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
> /home/pc/.rbenv/versions/2.5.3/bin/rake:23:in `load'
> /home/pc/.rbenv/versions/2.5.3/bin/rake:23:in `<main>'

My environments are

OS: Ubuntu16.04 x64
CRuby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
MRuby: latest
AndroidNKD: r20
ANDROID_NDK_HOME=/home/pc/android-ndk-r20
build_config.rb
```
MRuby::CrossBuild.new('android-arm64-v8a') do |conf|
  params = { 
    :arch => 'arm64-v8a', 
    :platform => 'android-24',
    :toolchain => :clang,
  }
  toolchain :android, params

  conf.linker.flags = %W(--sysroot="/home/pc/android-ndk-r20/platforms/android-24/arch-arm64")
  conf.linker.flags_before_libraries = %W(-gcc-toolchain "/home/pc/android-ndk-r20/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/" -target aarch64-none-linux-android -no-canonical-prefixes)

  conf.gembox 'default'
end
```

What am I missing and how to configure for x86 emulator?

**Comment by matz** [comment]
From the message "Don't know how to build task 'android-arm64-v8a'", it seems you have tried `rake android-arm64-v8a`. But `MRuby::CrossBuild.new` does not create a new task. You need to invoke `rake all` to compile.  

We need to more info to resolve the issue.

**Comment by IK-O** [comment]
rake all failed widh follow messages.

```
CC    src/backtrace.c -> build/android-arm64-v8a/src/backtrace.o
In file included from /home/pc/mruby/src/backtrace.c:7:
In file included from /home/pc/mruby/include/mruby.h:67:
/home/pc/mruby/include/mrbconf.h:151:11: fatal error: 'stdio.h' file not found
# include <stdio.h>
          ^~~~~~~~~

```

**Comment by matz** [comment]
It seems that your compiler cannot find the very basic header file `stdio.h`.
That indicates your compiler requires more configuration for include path.
I am sorry I don't know how to fix the compiler configuration in the Android simulator.

**Comment by IK-O** [comment]
I tried again referring to here 

https://qiita.com/kjunichi/items/f3d906feb7fe6239513f
(mrubyをAndroid Studioのエミュレーターで動かすためのlibmruby.aを作る)

build_config.rb
```
MRuby::CrossBuild.new('android_x86') do |conf|
    toolchain :android, {:arch => "x86_64",:platform => "android-21"}

    # include the default GEMs
    conf.gembox 'full-core'
end
```

On Ubuntu16.04 and MacOS, it failed with same error.

```
CC    mrbgems/mruby-compiler/core/codegen.c -> build/android_x86/mrbgems/mruby-compiler/core/codegen.o
/home/pc/mruby/mrbgems/mruby-compiler/core/codegen.c:7:10: fatal error: 
      'ctype.h' file not found
#include <ctype.h>
         ^~~~~~~~~
1 error generated.
rake aborted!
Command Failed: [/home/pc/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -MMD -MP -D__android__ -DANDROID --sysroot="/home/pc/android-ndk-r20/platforms/android-21/arch-x86_64" -target x86_64-none-linux-android -gcc-toolchain "/home/pc/android-ndk-r20/toolchains/x86_64-4.9/prebuilt/linux-x86_64" -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -DMRBGEM_MRUBY_COMPILER_VERSION=0.0.0 -I/home/pc/mruby/include -MMD -o /home/pc/mruby/build/android_x86/mrbgems/mruby-compiler/core/codegen.o -c /home/pc/mruby/mrbgems/mruby-compiler/core/codegen.c]
```

On Windows7, it failed with another error.
```
rake aborted!
No such file or directory - C:\Program Files\Android\android-ndk-r20/toolchains/llvm/prebuilt/windows*/bin/clang -MMD -MP -D__android__ -DANDRO
ID --sysroot="C:\Program Files\Android\android-ndk-r20/platforms/android-21/arch-x86_64" -target x86_64-none-linux-android -gcc-toolchain "C:\P
rogram Files\Android\android-ndk-r20/toolchains/x86_64-/prebuilt/windows*" -Wno-invalid-command-line-argument -Wno-unused-command-line-argument
 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -DMRBGEM_MRUBY_COMPILER_VERSION=0.0.0 -IC:/mruby2.0.
1/include -MMD -o C:/mruby2.0.1/build/android_x86/mrbgems/mruby-compiler/core/codegen.o -c C:/mruby2.0.1/mrbgems/mruby-compiler/core/codegen.c
```

Does anyone know how to fix this problem?

**Comment by matz** [comment]
Lack of `ctypes.h` or `clang` seems to be a serious installation error. Can other programs be compiled under the emulator?

**Comment by IK-O** [comment]
I didn't use emulator.
I just use MRuby and AndroidNDK to make libmruby.a for Android.

According to http://crimsonwoods.hatenablog.com/entry/2013/03/15/012550, MRuby can make libmruby.a for Android if path to AndroidNDK is set and configure build_config.rb.
It seems to need no other requirements although the article is very old.

**Comment by shuujii** [comment]
Can you build by GCC? (on Linux)

```ruby
MRuby::CrossBuild.new('android_x86') do |conf|
  toolchain :android, arch: "x86_64", platform: "android-21", toolchain: :gcc
  conf.gembox 'default'
end
```

**Comment by IK-O** [comment]
@shuujii 
Thanks. A step forward.

Error changed when I used his config.

```
CC    mrbgems/mruby-compiler/core/codegen.c -> build/android_x86/mrbgems/mruby-compiler/core/codegen.o
sh: 1: /home/pc/android-ndk-r20/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/x86_64-linux-android-gcc: not found
rake aborted!
```

There is no such gcc in newest NDK's toolchains directory.
I think I need to make standalone-toolchain of NDK, but after it, how to configure MRuby?

According to http://crimsonwoods.hatenablog.com/entry/2013/03/15/012550, there was ANDROID_STANDALONE_TOOLCHAIN in mruby/tasks/toolchains/android.rake, but not now.

**Comment by matz** [comment]
It depends on where you install Android NDK. When I install it (via Ubuntu `google-android-ndk-installer` package), I can find `x86_64-linux-android-gcc` at `/usr/lib/android-ndk/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/`.

**Comment by matz** [comment]
Define your NKD installation directory to the environment variable `ANDROID_NDK_HOME` (in the above case, `/usr/lib/android-ndk`) before invoking `rake`, e.g. `ANDROID_NDK_HOME=/usr/lib/android-ndk rake all`.

**Comment by shuujii** [comment]
I succeeded build by Android NDK r20 on Mac (It was just built, not tested).

#### custom_build_config.rb

```ruby
MRuby::Build.new do |conf|
  conf.toolchain :clang
  conf.gem core: 'mruby-bin-mrbc'
end

MRuby::CrossBuild.new('android_x86') do |conf|
  api = 21
  conf.toolchain :android, arch: "x86_64", platform: "android-#{api}"
  conf.gem core: 'mruby-print'
  conf.gem core: 'mruby-bin-mruby'
  conf.cc do |cc|
    cc.defines << "__ANDROID_API__=#{api}"
    cc.flags << "--sysroot=#{ENV['ANDROID_NDK_HOME']}/sysroot"
  end
end
```

#### Build

```shell
$ rake MRUBY_CONFIG=custom_build_config.rb ANDROID_NDK_HOME=/path/to/android_ndk_home
CC    src/array.c -> build/host/src/array.o
CC    src/backtrace.c -> build/host/src/backtrace.o
CC    src/class.c -> build/host/src/class.o
CC    src/codedump.c -> build/host/src/codedump.o
CC    src/compar.c -> build/host/src/compar.o
CC    src/crc.c -> build/host/src/crc.o
CC    src/debug.c -> build/host/src/debug.o
CC    src/dump.c -> build/host/src/dump.o
CC    src/enum.c -> build/host/src/enum.o
CC    src/error.c -> build/host/src/error.o
CC    src/etc.c -> build/host/src/etc.o
CC    src/fmt_fp.c -> build/host/src/fmt_fp.o
CC    src/gc.c -> build/host/src/gc.o
CC    src/hash.c -> build/host/src/hash.o
CC    src/init.c -> build/host/src/init.o
CC    src/kernel.c -> build/host/src/kernel.o
CC    src/load.c -> build/host/src/load.o
CC    src/numeric.c -> build/host/src/numeric.o
CC    src/object.c -> build/host/src/object.o
CC    src/pool.c -> build/host/src/pool.o
CC    src/print.c -> build/host/src/print.o
CC    src/proc.c -> build/host/src/proc.o
CC    src/range.c -> build/host/src/range.o
CC    src/state.c -> build/host/src/state.o
CC    src/string.c -> build/host/src/string.o
CC    src/symbol.c -> build/host/src/symbol.o
CC    src/variable.c -> build/host/src/variable.o
CC    src/version.c -> build/host/src/version.o
CC    src/vm.c -> build/host/src/vm.o
CC    mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.c -> build/host/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o
CC    mrbgems/mruby-compiler/core/codegen.c -> build/host/mrbgems/mruby-compiler/core/codegen.o
YACC  mrbgems/mruby-compiler/core/parse.y -> build/host/mrbgems/mruby-compiler/core/y.tab.c
CC    build/host/mrbgems/mruby-compiler/core/y.tab.c -> build/host/mrbgems/mruby-compiler/core/y.tab.o
AR    build/host/lib/libmruby_core.a 
ar: creating archive /Users/shuujii/.ghq/github.com/mruby/mruby/build/host/lib/libmruby_core.a
LD    build/host/bin/mrbc 
GEN   *.rb -> build/host/mrblib/mrblib.c
      MRBC mrblib/00class.rb 
      MRBC mrblib/10error.rb 
      MRBC mrblib/array.rb 
      MRBC mrblib/compar.rb 
      MRBC mrblib/enum.rb 
      MRBC mrblib/hash.rb 
      MRBC mrblib/kernel.rb 
      MRBC mrblib/numeric.rb 
      MRBC mrblib/range.rb 
      MRBC mrblib/string.rb 
      MRBC mrblib/symbol.rb 
CC    build/host/mrblib/mrblib.c -> build/host/mrblib/mrblib.o
CC    build/host/mrbgems/gem_init.c -> build/host/mrbgems/gem_init.o
AR    build/host/lib/libmruby.a 
ar: creating archive /Users/shuujii/.ghq/github.com/mruby/mruby/build/host/lib/libmruby.a
CC    src/array.c -> build/android_x86/src/array.o
CC    src/backtrace.c -> build/android_x86/src/backtrace.o
CC    src/class.c -> build/android_x86/src/class.o
CC    src/codedump.c -> build/android_x86/src/codedump.o
CC    src/compar.c -> build/android_x86/src/compar.o
CC    src/crc.c -> build/android_x86/src/crc.o
CC    src/debug.c -> build/android_x86/src/debug.o
CC    src/dump.c -> build/android_x86/src/dump.o
CC    src/enum.c -> build/android_x86/src/enum.o
CC    src/error.c -> build/android_x86/src/error.o
CC    src/etc.c -> build/android_x86/src/etc.o
CC    src/fmt_fp.c -> build/android_x86/src/fmt_fp.o
CC    src/gc.c -> build/android_x86/src/gc.o
CC    src/hash.c -> build/android_x86/src/hash.o
CC    src/init.c -> build/android_x86/src/init.o
CC    src/kernel.c -> build/android_x86/src/kernel.o
CC    src/load.c -> build/android_x86/src/load.o
CC    src/numeric.c -> build/android_x86/src/numeric.o
CC    src/object.c -> build/android_x86/src/object.o
CC    src/pool.c -> build/android_x86/src/pool.o
CC    src/print.c -> build/android_x86/src/print.o
CC    src/proc.c -> build/android_x86/src/proc.o
CC    src/range.c -> build/android_x86/src/range.o
CC    src/state.c -> build/android_x86/src/state.o
CC    src/string.c -> build/android_x86/src/string.o
CC    src/symbol.c -> build/android_x86/src/symbol.o
CC    src/variable.c -> build/android_x86/src/variable.o
CC    src/version.c -> build/android_x86/src/version.o
CC    src/vm.c -> build/android_x86/src/vm.o
GEN   *.rb -> build/android_x86/mrblib/mrblib.c
      MRBC mrblib/00class.rb 
      MRBC mrblib/10error.rb 
      MRBC mrblib/array.rb 
      MRBC mrblib/compar.rb 
      MRBC mrblib/enum.rb 
      MRBC mrblib/hash.rb 
      MRBC mrblib/kernel.rb 
      MRBC mrblib/numeric.rb 
      MRBC mrblib/range.rb 
      MRBC mrblib/string.rb 
      MRBC mrblib/symbol.rb 
CC    build/android_x86/mrblib/mrblib.c -> build/android_x86/mrblib/mrblib.o
CC    mrbgems/mruby-print/src/print.c -> build/android_x86/mrbgems/mruby-print/src/print.o
      MRBC mrbgems/mruby-print/mrblib/print.rb 
CC    build/android_x86/mrbgems/mruby-print/gem_init.c -> build/android_x86/mrbgems/mruby-print/gem_init.o
CC    mrbgems/mruby-compiler/core/codegen.c -> build/android_x86/mrbgems/mruby-compiler/core/codegen.o
YACC  mrbgems/mruby-compiler/core/parse.y -> build/android_x86/mrbgems/mruby-compiler/core/y.tab.c
CC    build/android_x86/mrbgems/mruby-compiler/core/y.tab.c -> build/android_x86/mrbgems/mruby-compiler/core/y.tab.o
CC    mrbgems/mruby-error/src/exception.c -> build/android_x86/mrbgems/mruby-error/src/exception.o
CC    build/android_x86/mrbgems/mruby-error/gem_init.c -> build/android_x86/mrbgems/mruby-error/gem_init.o
CC    build/android_x86/mrbgems/gem_init.c -> build/android_x86/mrbgems/gem_init.o
AR    build/android_x86/lib/libmruby.a 
/Users/shuujii/app/android/android-ndk-r20/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/bin/x86_64-linux-android-ar: creating /Users/shuujii/.ghq/github.com/mruby/mruby/build/android_x86/lib/libmruby.a
CC    mrbgems/mruby-bin-mruby/tools/mruby/mruby.c -> build/android_x86/mrbgems/mruby-bin-mruby/tools/mruby/mruby.o
LD    build/android_x86/bin/mruby 

Build summary:

================================================
      Config Name: host
 Output Directory: build/host
         Binaries: mrbc
    Included Gems:
             mruby-compiler - mruby compiler library
             mruby-bin-mrbc - mruby compiler executable
================================================

================================================
      Config Name: android_x86
 Output Directory: build/android_x86
    Included Gems:
             mruby-print - standard print/puts/p
             mruby-compiler - mruby compiler library
             mruby-error - extensional error handling
             mruby-bin-mruby - mruby command
               - Binaries: mruby
================================================

**Comment by IK-O** [comment]
@shuujii Awesome!!

I too succeeded build on both Ubuntu16.04 and MacOS, using your configure.

I pretty thank your great help.

I hope his configure is published as a correct example on a prominent place.

**Comment by IK-O** [comment]
It worked on both Android Studio emurator and real Android device.
