### ISSUE TITLE
64-bit integer literal does not work without presym

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#5369]
### Example

```ruby
# conf.rb
MRuby::Lockfile.disable
MRuby::Build.new do |conf|
  conf.toolchain
  conf.disable_presym
  conf.enable_debug
  conf.enable_sanitizer "address,leak,undefined"
  conf.gem core: "mruby-bin-mruby"
end
```

```console
$ echo 'def int64; 0x100000000 end' > mrblib/int64.rb
$ rake CONFIG=conf.rb -m
$ bin/mruby -e int64
AddressSanitizer:DEADLYSIGNAL
=================================================================
==56942==ERROR: AddressSanitizer: SEGV on unknown address 0x0000fffffff0 (pc 0x7fb6252d9a06 bp 0x0000fffffff0 sp 0x7ffd0fbd4110 T0)
==56942==The signal is caused by a WRITE memory access.
    #0 0x7fb6252d9a05  (/lib/x86_64-linux-gnu/libasan.so.5+0x28a05)
    #1 0x7fb6253be798 in __interceptor_free (/lib/x86_64-linux-gnu/libasan.so.5+0x10d798)
    #2 0x5585ea9189e3 in mrb_default_allocf !/mruby/src/state.c:64
    #3 0x5585ea817c90 in mrb_free /mruby/src/gc.c:290
    #4 0x5585ea919749 in mrb_irep_free /mruby/src/state.c:158
    #5 0x5585ea918fb2 in mrb_irep_decref /mruby/src/state.c:128
    #6 0x5585ea91922c in mrb_irep_cutref /mruby/src/state.c:143
    #7 0x5585ea81f7fb in obj_free /mruby/src/gc.c:885
    #8 0x5585ea819aa6 in free_heap /mruby/src/gc.c:435
    #9 0x5585ea819b23 in mrb_gc_destroy /mruby/src/gc.c:444
    #10 0x5585ea919f98 in mrb_close /mruby/src/state.c:194
    #11 0x5585ea8161f3 in cleanup /mruby/mrbgems/mruby-bin-mruby/tools/mruby/mruby.c:262
    #12 0x5585ea817238 in main /mruby/mrbgems/mruby-bin-mruby/tools/mruby/mruby.c:368
    #13 0x7fb62462a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #14 0x5585ea811a4d in _start (/mruby/bin/mruby+0x2a3a4d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libasan.so.5+0x28a05)
==56942==ABORTING
```

**Comment by shuujii** [comment]
There was some error in the ASAN report, so I fixed it.
