### ISSUE TITLE
error: implicit declaration of function 'clock_gettime' [-Werror=implicit-function-declaration]

### ISSUE THREAD

**Issue by tinybeat** [mruby/mruby#5784]
I try to complie the latest mruby-3.1.0 on Windows11 with default configuation
```
D:\software\language\mruby-3.1.0>rake
CC    mrbgems/mruby-time/src/time.c -> build/host/mrbgems/mruby-time/src/time.o
D:/software/language/mruby-3.1.0/mrbgems/mruby-time/src/time.c: In function 'current_mrb_time':
D:/software/language/mruby-3.1.0/mrbgems/mruby-time/src/time.c:385:5: error: implicit declaration of function 'clock_gettime' [-Werror=implicit-function-declaration]
  385 |     clock_gettime(CLOCK_REALTIME, &ts);
      |     ^~~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
rake aborted!
Command failed with status (1): [gcc -MMD -c -std=gnu99 -g -O3 -Wall -Wunde...]
D:/software/language/mruby-3.1.0/lib/mruby/build/command.rb:37:in `_run'
D:/software/language/mruby-3.1.0/lib/mruby/build/command.rb:99:in `run'
D:/software/language/mruby-3.1.0/lib/mruby/build/command.rb:120:in `block (2 levels) in define_rules'
D:/software/language/mruby-3.1.0/Rakefile:42:in `block in <top (required)>'
Tasks: TOP => build => D:/software/language/mruby-3.1.0/build/host/lib/libmruby.a => D:/software/language/mruby-3.1.0/build/host/mrbgems/mruby-time/src/time.o
(See full trace by running task with --trace)
```
is there any way to solve it

**Comment by matz** [comment]
Could you provide us more information please? The default configuration (build_config/default.rb) depends on gcc, so you must have installed some gcc compiler on your machine, right?

But if you have fully installed mingw or cygwin, you must have access to clock_gettime. So I need your installation configuration, including compiler, library, etc.

**Comment by tinybeat** [comment]
Yes, i‘ve installed TDM-GCC 10.3.0-2 and it was downloaded from the TDM-GCC's official website.I just added its path to the environment variable and didn't change other configuration.

```
D:\software\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\10.3.0\include>ls
ISO_Fortran_binding.h  avx512vlbwintrin.h            emmintrin.h     pconfigintrin.h  tbmintrin.h
acc_prof.h             avx512vldqintrin.h            enqcmdintrin.h  pkuintrin.h      tgmath.h
adxintrin.h            avx512vlintrin.h              f16cintrin.h    pmmintrin.h      tmmintrin.h
ammintrin.h            avx512vnniintrin.h            float.h         popcntintrin.h   unwind.h
avx2intrin.h           avx512vnnivlintrin.h          fma4intrin.h    prfchwintrin.h   vaesintrin.h
avx5124fmapsintrin.h   avx512vp2intersectintrin.h    fmaintrin.h     quadmath.h       varargs.h
avx5124vnniwintrin.h   avx512vp2intersectvlintrin.h  fxsrintrin.h    quadmath_weak.h  vpclmulqdqintrin.h
avx512bf16intrin.h     avx512vpopcntdqintrin.h       gcov.h          rdseedintrin.h   waitpkgintrin.h
avx512bf16vlintrin.h   avx512vpopcntdqvlintrin.h     gfniintrin.h    rtmintrin.h      wbnoinvdintrin.h
avx512bitalgintrin.h   avxintrin.h                   ia32intrin.h    sgxintrin.h      wmmintrin.h
avx512bwintrin.h       bmi2intrin.h                  immintrin.h     shaintrin.h      x86intrin.h
avx512cdintrin.h       bmiintrin.h                   iso646.h        smmintrin.h      xmmintrin.h
avx512dqintrin.h       bmmintrin.h                   lwpintrin.h     ssp              xopintrin.h
avx512erintrin.h       c++                           lzcntintrin.h   stdalign.h       xsavecintrin.h
avx512fintrin.h        cet.h                         mm3dnow.h       stdarg.h         xsaveintrin.h
avx512ifmaintrin.h     cetintrin.h                   mm_malloc.h     stdatomic.h      xsaveoptintrin.h
avx512ifmavlintrin.h   cldemoteintrin.h              mmintrin.h      stdbool.h        xsavesintrin.h
avx512pfintrin.h       clflushoptintrin.h            movdirintrin.h  stddef.h         xtestintrin.h
avx512vbmi2intrin.h    clwbintrin.h                  mwaitxintrin.h  stdfix.h
avx512vbmi2vlintrin.h  clzerointrin.h                nmmintrin.h     stdint-gcc.h
avx512vbmiintrin.h     cpuid.h                       omp.h           stdint.h
avx512vbmivlintrin.h   cross-stdarg.h                openacc.h       stdnoreturn.h

D:\software\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\10.3.0\include>gcc -v
 specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=D:/software/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/10.3.0/lto-wrapper.exe
x86_64-w64-mingw32
../../../src/gcc-git-10.3.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,jit,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --enable-libstdcxx-threads --enable-libstdcxx-time=yes --enable-mingw-wildcard --with-gnu-ld --disable-werror --enable-nls --disable-win32-registry --enable-large-address-aware --disable-rpath --disable-symvers --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=https://github.com/jmeubank/tdm-gcc/issues
posix
Supported LTO compression algorithms: zlib zstd
gcc  10.3.0 (tdm64-1)
```
Here's the library and the version of gcc.

**Comment by matz** [comment]
I have no idea. mruby-time use clock_gettime only if:

* _POSIX_TIMERS is defined and its value is more than 1
* CLOCK_REALTIME is defined

Your error suggests that your header files provide constants required for clock_gettime() and lack a prototype for the function.
This is insane.

As far as I read in [this page](https://bytemeta.vip/repo/jmeubank/tdm-gcc/issues/8), TDM-GCC 10.3.0 touched prototypes regarding the clock_gettime() etc. So maybe it is caused by their bug.

For the workaround, use MinGW instead of TDM-GCC.

**Comment by tinybeat** [comment]
You're right, it's caused by their bug.

I missed one thing that the first time i used TDM-GCC 9.2.0 to complie it(use the command `rake` in the mruby-3.1.0 folder path) and i got the error message. Then i changed the TDM-GCC 10.3.0 to complie in the same folder path and the error message still occured.

This time, with your response, i delete the mruby-3.1.0 folder and unzip mruby-3.1.0.zip again and the compilation process is successful.

It seems that once `rake` get an error during compilation, the second time is will just show last error. And the `complie.md` and `rake -v` don't mention how to complie again when an error occurs.

**Comment by matz** [comment]
I recommend to type `rake clean` often when you hit the errors. I will write this tip somewhere in the documentation.
