### ISSUE TITLE
cross build error for NetBSD/arm

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#5860]
I use conf.gembox 'default' on cross build on FreeBSD/amd64 for NetBSD/arm.

I have error no libreadline and no libncurses.

I seem cause of mrbgems/mruby-bin-mirb/mrbgem.rake.

I want use libedit.

Also NetBSD 9.99 libedit need libtermcap.

If you have advice, please let me know.

Thanks

**Comment by matz** [comment]
Show us the error messages.

**Comment by yamori813** [comment]
```
% rake MRUBY_CONFIG=netbsd
LD    build/cross-netbsd-arm/bin/mirb 
/usr/home/hiroki/netbsd-tools/earmv4/lib/gcc/armv4--netbsdelf-eabi/10.4.0/../../../../armv4--netbsdelf-eabi/bin/ld: cannot find -lreadline
/usr/home/hiroki/netbsd-tools/earmv4/lib/gcc/armv4--netbsdelf-eabi/10.4.0/../../../../armv4--netbsdelf-eabi/bin/ld: cannot find -lncurses
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [/usr/home/hiroki/netbsd-tools/earmv4/bin/a...]
/usr/home/hiroki/mruby-3.1.0/lib/mruby/build/command.rb:37:in `_run'
/usr/home/hiroki/mruby-3.1.0/lib/mruby/build/command.rb:217:in `run'
/usr/home/hiroki/mruby-3.1.0/tasks/bin.rake:17:in `block (4 levels) in <top (required)>'
/usr/home/hiroki/mruby-3.1.0/Rakefile:42:in `block in <top (required)>'
Tasks: TOP => build => /usr/home/hiroki/mruby-3.1.0/build/cross-netbsd-arm/bin/mirb
(See full trace by running task with --trace)
```

**Comment by dearblue** [comment]
I don't know if this is correct, but how about replacing the library by calling `mruby-bin-mirb` with a block before `gembox "default"`, as in the following example?

```ruby
MRuby::CrossBuild.new("netbsd") do |conf|
  conf.toolchain "gcc"
  conf.gem core: "mruby-bin-mirb" do |spec|
    spec.linker.libraries = %w(edit termcap)
  end
  conf.gembox "default"
end
```

---

`mruby-bin-mirb` cannot automatically cross build to/from NetBSD for reasons determined by `RUBY_PLATFORM`.

https://github.com/mruby/mruby/blob/1bec3392300e99ea037a8e18aa9694c83390cea3/mrbgems/mruby-bin-mirb/mrbgem.rake#L21-L24

Some improvement is needed, but I have no ideas.

**Comment by yamori813** [comment]
This replacing workaround is fine on my environment.

**Comment by yamori813** [comment]
Same problem on this case.

https://qiita.com/yamori813/items/5153efb2ec0a23bfa7fb

I think good that is RUBY_PLATFORM set "NetBSD" at build_config. And use is value in mrbgem.rake. But not valid RUBY_PLATFORM in mruby-uv mrbgem.rake.

**Comment by matz** [comment]
Probably, we need to distinguish host and target during the build (and use target info instead of RUBY_PLATFORM).

**Comment by dearblue** [comment]
The `RUBY_PLATFORM` constant is defined by Ruby, so I don't think it is desirable to make any changes to it.
I also think that introducing another constant to check the build target is undesirable, as it leads to writing code that assumes the environment to be a prerequisite by name.

How about introducing methods for "feature check" (such as `have_library` or `have_macro`) defined in Ruby's `mkmf.rb` library?
However, I would like to have a mechanism to avoid this, since there is a possibility that these methods will be called every time just by `rake clean`, for example.

Example?:

```ruby
# mygem/mrbgem.rake
MRuby::Gem::Specification.new("mygem") do |spec|
  ....
  spec.before_compile do
    case
    when spec.have_library "edit"
      ....
    when spec.have_library "readline"
      ....
    else
      ....
    end
  end
end
```

**Comment by yamori813** [comment]
Sorry Now I not use cross compile for NetBSD. I do only self compile on NetBSD.
