### ISSUE TITLE
mruby build fails under mrbgems directory

### ISSUE THREAD

**Issue by takumin** [mruby/mruby#6029]
If the mrbgems directory name is included above the mruby directory, the build will always fail.

```
$ git clone --branch master --depth 1 https://github.com/mruby/mruby.git /tmp/mrbgems/mruby
$ cd /tmp/mrbgems/mruby
$ rake

...snip...

CPP   mrbgems/mruby-time/src/time.c -> build/host/mrbgems/mruby-time/src/time.pi
/tmp/mrbgems/mruby/mrbgems/mruby-time/src/time.c:11:10: fatal error: mruby/time.h: No such file or directory
   11 | #include <mruby/time.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
rake aborted!
Command failed with status (1): [gcc -E -P -std=gnu99 -g -O3 -Wall -Wundef ...]
/tmp/mrbgems/mruby/lib/mruby/build/command.rb:33:in `_run'
/tmp/mrbgems/mruby/lib/mruby/build/command.rb:95:in `run'
/tmp/mrbgems/mruby/lib/mruby/build/command.rb:116:in `block (2 levels) in define_rules'
Tasks: TOP => default => all => gensym => /tmp/mrbgems/mruby/build/host/presym => /tmp/mrbgems/mruby/build/host/mrbgems/mruby-time/src/time.pi
(See full trace by running task with --trace)
```

**Comment by matz** [comment]
The reason for the issue is `mrbgems` in the parent directory. For a workaround, rename the directory.
We will fix the issue in the future.

**Comment by takumin** [comment]
I built with 5e777958dde7c71b321d9eaaa19cdc6d5955bf6a and confirmed that this issue has been resolved.
If the issue number in the Git comment is just wrong, I would like to close this issue.

**Comment by matz** [comment]
Wrong issue number fixed.  Thank you.
